### ISSUE TITLE
Elasticsearch fails service port validation

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#10418]
Elastic search fails to come up on my (fairly recent) cluster with:
```
  FirstSeen				LastSeen			Count	From					SubobjectPath	Reason			Message
  Fri, 26 Jun 2015 11:30:42 -0700	Fri, 26 Jun 2015 11:41:51 -0700	4	{kubelet e2e-test-beeps-minion-212j}			failedValidation	Error validating pod elasticsearch-logging-v1-z7iyt.default from api, ignoring: spec.containers[0].ports[1].name: invalid value 'es-transport-port': must be a IANA_SVC_NAME (at most 15 characters, matching regex [a-z0-9]([a-z0-9-]*[a-z0-9])* and it must containts at least one letter [a-z], hypens cannot be adjacent to other hyphens): e.g. "http"

```
This leads to a kibana restart loop (the pod stays in running but the container keeps restarting, and the kubelet keeps updating restart count)
 
```
beeps@e2e-test-beeps-minion-tth9:~$ sudo docker logs a04729116dac
ELASTICSEARCH_URL=http://elasticsearch-logging:9200
{"@timestamp":"2015-06-26T18:35:26.196Z","level":"error","message":"Request Timeout after 1500ms","node_env":"production","error":{"message":"Request Timeout after 1500ms","name":"Error","stack":"Error: Request Timeout after 1500ms\n  at [object Object].<anonymous> (/kibana-4.0.2-linux-x64/src/node_modules/elasticsearch/src/lib/transport.js:282:15)\n  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)\n"}}
{"@timestamp":"2015-06-26T18:35:26.198Z","level":"fatal","message":"Request Timeout after 1500ms","node_env":"production","error":{"message":"Request Timeout after 1500ms","name":"Error","stack":"Error: Request Timeout after 1500ms\n  at [object Object].<anonymous> (/kibana-4.0.2-linux-x64/src/node_modules/elasticsearch/src/lib/transport.js:282:15)\n  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)\n"}}
```
@satnam6502 

I don't think we've changed the json recently, so it's probalby new validation  (https://github.com/GoogleCloudPlatform/kubernetes/blob/54a3ebef3c6bcc6c4e4d7a45be339af62c0358c9/pkg/api/validation/validation.go#L52).

I am puzzled by something, it seems like the es rc skipped validation, because get rc shows me:
```
12:06:32-beeps~/goproj/src/github.com/GoogleCloudPlatform/kubernetes] (density_logging_2)$ k get rc 
CONTROLLER                     CONTAINER(S)            IMAGE(S)                                          SELECTOR                                   REPLICAS
elasticsearch-logging-v1       elasticsearch-logging   gcr.io/google_containers/elasticsearch:1.4        k8s-app=elasticsearch-logging,version=v1   2

```
but get pods shows the validation error. So the pods failed validation but the rc didn't, hrm.

**Comment by roberthbailey** [comment]
I just merged a PR this morning that added extra validation and the e2e tests were still green.... Is this something that isn't covered by the elastic search e2e tests?

**Comment by satnam6502** [comment]
See https://github.com/GoogleCloudPlatform/kubernetes/issues/10452 and fix.
Is it really the case we can't dashes in the port name?

**Comment by satnam6502** [comment]
@roberthbailey This should have been caught by e2e tests. I think the e2e logging test is in the flaky group @quinton-hoole

**Comment by bprashanth** [comment]
This was fixed after discussion in the spinoff bug and the associated pr
