### ISSUE TITLE
Not able to deploy kubernetes on GCE

### ISSUE THREAD

**Issue by svennela** [GoogleCloudPlatform/kubernetes#10846]
Hi, 

I am trying to deploy kubernetes on GCE and running into below issue.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md#getting-started-with-your-cluster

gcloud compute networks create --project firstproject-989 default --range 10.240.0.0/16

Traceback (most recent call last):
  File "/Users/svennela/workspace/tools/workspace/tools/google-cloud-sdk/lib/googlecloudsdk/gcloud/gcloud.py", line 85, in <module>
    from googlecloudsdk.calliope import base
  File "/Users/svennela/workspace/tools/workspace/tools/google-cloud-sdk/lib/googlecloudsdk/calliope/base.py", line 8, in <module>
    from googlecloudsdk.calliope import usage_text
  File "/Users/svennela/workspace/tools/workspace/tools/google-cloud-sdk/lib/googlecloudsdk/calliope/usage_text.py", line 12, in <module>
    from googlecloudsdk.calliope import arg_parsers
  File "/Users/svennela/workspace/tools/workspace/tools/google-cloud-sdk/lib/googlecloudsdk/calliope/arg_parsers.py", line 43, in <module>
    from googlecloudsdk.core import log
  File "/Users/svennela/workspace/tools/workspace/tools/google-cloud-sdk/lib/googlecloudsdk/core/log.py", line 14, in <module>
    from googlecloudsdk.core import properties
  File "/Users/svennela/workspace/tools/workspace/tools/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 11, in <module>
    from googlecloudsdk.core import config
  File "/Users/svennela/workspace/tools/workspace/tools/google-cloud-sdk/lib/googlecloudsdk/core/config.py", line 5, in <module>
    import json
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 108, in <module>
    from .decoder import JSONDecoder
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 24, in <module>
    NaN, PosInf, NegInf = _floatconstants()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 18, in _floatconstants
    _BYTES = '7FF80000000000007FF0000000000000'.decode('hex')
LookupError: unknown encoding: hex

**Comment by roberthbailey** [comment]
What version of python do you have installed? If you run a python shell and try to decode a string into hex, do you get the same error? On my machine:

```
$ python
Python 2.7.9 (default, Jan 26 2015, 13:02:24) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> '7FF80000000000007FF0000000000000'.decode('hex')
'\x7f\xf8\x00\x00\x00\x00\x00\x00\x7f\xf0\x00\x00\x00\x00\x00\x00'
>>> 
```

**Comment by svennela** [comment]
I am able to get pass that error now i am running into below error.


Starting master and configuring firewalls
ERROR: (gcloud.compute.disks.create) Some requests did not succeed:
 - The resource 'projects/firstproject-989/zones/us-central1-b/diskTypes/pd-ssd' was not found

**Comment by svennela** [comment]
I have upgrade to paid account. it works..:)

**Comment by hingstarne** [comment]
In cluster/gce/config-default.sh
change pd-ssd to pd-standard and you would be able to use the free tier from gce with the installer
