### ISSUE TITLE
Cannot deploy on AWS with v1.0.0 release candidate

### ISSUE THREAD

**Issue by frosenberg** [GoogleCloudPlatform/kubernetes#11297]
I used the latest release to deploy on EC2. It fails as follows (just showing the relevant parts of the CLI output):

```
[...]
Creating minion configuration
Creating autoscaling group
 0 minions started; waiting
 0 minions started; waiting
 0 minions started; waiting
 0 minions started; waiting
 1 minions started; waiting
 1 minions started; waiting
 2 minions started; ready
Waiting 3 minutes for cluster to settle
..................Re-running salt highstate
Waiting for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start
  up.

Kubernetes cluster created.
Wrote config for aws_kubernetes to /Users/florian/.kube/config
Sanity checking cluster...
Attempt 1 to check Docker on node @ 52.28.128.92 ...not working yet
Attempt 2 to check Docker on node @ 52.28.128.92 ...not working yet
Attempt 3 to check Docker on node @ 52.28.128.92 ...not working yet
Attempt 4 to check Docker on node @ 52.28.128.92 ...not working yet
Attempt 5 to check Docker on node @ 52.28.128.92 ...not working yet
Attempt 6 to check Docker on node @ 52.28.128.92 ...not working yet
Attempt 7 to check Docker on node @ 52.28.128.92 ...not working yet
Attempt 8 to check Docker on node @ 52.28.128.92 ...not working yet
Attempt 9 to check Docker on node @ 52.28.128.92 ...not working yet
Attempt 10 to check Docker on node @ 52.28.128.92 ...not working yet
Attempt 11 to check Docker on node @ 52.28.128.92 ...not working yet

Your cluster is unlikely to work correctly.
Please run ./cluster/kube-down.sh and re-create the
cluster. (sorry!)
``` 

Here are the environment variables I use:
```
export KUBERNETES_PROVIDER=aws
export KUBE_AWS_ZONE=eu-central-1a
export NUM_MINIONS=2
export MINION_SIZE=m3.medium
export AWS_S3_REGION=eu-central-1
export INSTANCE_PREFIX=k8s
```

The minion has the following content in the salt log:
```
root@ip-172-20-0-53:~# cat /var/log/salt/minion 
2015-07-15 10:00:26,226 [salt.state       ][ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1533, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/sysctl.py", line 56, in present
    configured = __salt__['sysctl.show'](config_file=True)
  File "/usr/lib/python2.7/dist-packages/salt/modules/linux_sysctl.py", line 86, in show
    for line in salt.utils.fopen(config_file_path):
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1065, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 2] No such file or directory: '/etc/sysctl.d/99-salt.conf'

2015-07-15 10:00:34,989 [salt.loaded.int.module.cmdmod][ERROR   ] Command 'runlevel /run/utmp' failed with return code: 1
2015-07-15 10:00:34,989 [salt.loaded.int.module.cmdmod][ERROR   ] output: Too many arguments.
2015-07-15 10:00:35,117 [salt.loaded.int.module.cmdmod][ERROR   ] Command 'service docker status' failed with return code: 3
2015-07-15 10:00:35,117 [salt.loaded.int.module.cmdmod][ERROR   ] output: * docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2015-07-15 10:00:35 UTC; 18ms ago
     Docs: http://docs.docker.com
  Process: 19728 ExecStart=/usr/bin/docker -d -H fd:// $DOCKER_OPTS (code=exited, status=1/FAILURE)
 Main PID: 19728 (code=exited, status=1/FAILURE)
2015-07-15 10:00:42,288 [salt.state       ][ERROR   ] The named service kubelet is not available
2015-07-15 10:00:44,836 [salt.state       ][ERROR   ] The named service kube-proxy is not available
```

I have been seeing this in older version too (v0.21.2).

**Comment by erictune** [comment]
@justinsb

**Comment by roberthbailey** [comment]
@brendandburns

**Comment by preillyme** [comment]
FWIW — I'm seeing a similar issue in our testing as well.

**Comment by justinsb** [comment]
I will try to reproduce

**Comment by preillyme** [comment]
I was able to get it working now following: https://github.com/GoogleCloudPlatform/kubernetes/blob/v1.0.0/docs/getting-started-guides/aws.md

**Comment by justinsb** [comment]
I suspect the problem is the S3 bucket being in a non-default region, I haven't tested this as much.  But I will try to figure it out.

**Comment by frosenberg** [comment]
@justinsb you think if I switch out the S3 location to default (i.e., unset the env var that I use), it should work. 

I can try that as well but tbh I see no correlation between the salt error and the S3 location. But I'm no expert here, just a user :)

**Comment by justinsb** [comment]
Hmmm .. it came up for me, even with the S3 bucket being in a different region.

Do you still have a non-working cluster?  Can you try running `systemctl status docker` on 52.28.128.92 so we can see the status of docker?

The error messages from kubelet are mostly known:

* No such file or directory: '/etc/sysctl.d/99-salt.conf' is fixed in #10401, but I think mostly harmless.
* The messages about kubelet & kube-proxy are just salt saying the service isn't installed before installing it

The docker message I'm not so sure about, which is why I'd like to see the output from systemctl status docker!

**Comment by justinsb** [comment]
@frosenberg so that was my theory, but I am no longer convinced, as it worked for me.  And the salt files come from S3, so if that was the problem I suspect we would fail much earlier.  It looks more like something went wrong with docker startup.  Output from systemctl status docker would be the next step, I believe.

**Comment by frosenberg** [comment]
@preillyme if you followed the procedure, I guess you installed v0.21.1, right?

**Comment by frosenberg** [comment]
Just followed the aws docs and installed v0.21.1. Same issue here. Trying version 1.0.0 now.

Docker fails to come up. Here is the upstart log `/var/log/upstart/docker.log`:

```
root@ip-172-20-0-193:~# cat /var/log/upstart/docker.log 
Waiting for /var/run/docker.sock
INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
INFO[0000] +job init_networkdriver()                    
no such network interface
INFO[0000] -job init_networkdriver() = ERR (1)          
FATA[0000] Shutting down daemon due to errors: no such network interface 
```
The same entry keeps repeated in the log.

The `/var/log/salt/minion` log shows this:
root@ip-172-20-0-193:~# cat /var/log/salt/minion 
2015-07-15 20:39:07,796 [salt.loaded.int.module.cmdmod][ERROR   ] Command 'service kubelet status' failed with return code: 3
2015-07-15 20:39:07,797 [salt.loaded.int.module.cmdmod][ERROR   ] output:  * kubelet is not running
2015-07-15 20:39:10,021 [salt.loaded.int.module.cmdmod][ERROR   ] Command 'service kube-proxy status' failed with return code: 3
2015-07-15 20:39:10,022 [salt.loaded.int.module.cmdmod][ERROR   ] output:  * kube-proxy is not running
2015-07-15 20:39:14,996 [salt.loaded.int.module.cmdmod][ERROR   ] Command 'crontab -l | grep "* * * * * /etc/monit/monit_watcher.sh 2>&1 | logger"' failed with return code: 1
2015-07-15 20:39:14,997 [salt.loaded.int.module.cmdmod][ERROR   ] output: no crontab for root
2015-07-15 20:39:21,636 [salt.loaded.int.module.cmdmod][ERROR   ] Command 'service docker start' failed with return code: 1
2015-07-15 20:39:21,636 [salt.loaded.int.module.cmdmod][ERROR   ] output: start: Job failed to start
2015-07-15 20:39:21,641 [salt.state       ][ERROR   ] Service docker is already disabled, and is dead
2015-07-15 20:39:23,469 [salt.loaded.int.module.cmdmod][ERROR   ] Command 'service kubelet status' failed with return code: 1
2015-07-15 20:39:23,469 [salt.loaded.int.module.cmdmod][ERROR   ] output:  * kubelet is not running

**Comment by frosenberg** [comment]
Just ran a test with v1.0.0 (distro 'vivid'). It fails as well with docker not coming up.

```
root@ip-172-20-0-71:~# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2015-07-15 21:25:04 UTC; 760ms ago
     Docs: http://docs.docker.com
  Process: 29131 ExecStart=/usr/bin/docker -d -H fd:// $DOCKER_OPTS (code=exited, status=1/FAILURE)
 Main PID: 29131 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/docker.service

Jul 15 21:25:04 ip-172-20-0-71 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul 15 21:25:04 ip-172-20-0-71 systemd[1]: Unit docker.service entered failed state.
Jul 15 21:25:04 ip-172-20-0-71 systemd[1]: docker.service failed.
```

Any clue? Cloud the ubuntu image in region in eu-central-1 be busted? I give it another try in the us-east region.

**Comment by frosenberg** [comment]
Ran the whole process in us-east-1 again. Same issue. Some more log information from syslog:

```
Jul 15 21:51:45 ubuntu systemd[1]: docker.service holdoff time over, scheduling restart.
Jul 15 21:51:45 ubuntu systemd[1]: Stopping Docker Socket for the API.
Jul 15 21:51:45 ubuntu systemd[1]: Starting Docker Socket for the API.
Jul 15 21:51:45 ubuntu kubelet[29715]: I0715 21:51:45.107995   29715 manager.go:163] Version: {KernelVersion:3.19.0-20-generic ContainerOsVersion:Ubuntu 15.04 DockerVersion:Unknown CadvisorVersion:0.15.1}
Jul 15 21:51:45 ubuntu kubelet[29715]: I0715 21:51:45.108511   29715 aws.go:483] Zone not specified in configuration file; querying AWS metadata service
Jul 15 21:51:45 ubuntu systemd[1]: Listening on Docker Socket for the API.
Jul 15 21:51:45 ubuntu systemd[1]: Started Docker Application Container Engine.
Jul 15 21:51:45 ubuntu systemd[1]: Starting Docker Application Container Engine...
Jul 15 21:51:45 ubuntu docker[29723]: time="2015-07-15T21:51:45Z" level=info msg="+job serveapi(fd://)"
Jul 15 21:51:45 ubuntu docker[29723]: time="2015-07-15T21:51:45Z" level=info msg="Listening for HTTP on fd ()"
Jul 15 21:51:45 ubuntu docker[29723]: time="2015-07-15T21:51:45Z" level=info msg="+job init_networkdriver()"
Jul 15 21:51:45 ubuntu docker[29723]: no such network interface
Jul 15 21:51:45 ubuntu docker[29723]: time="2015-07-15T21:51:45Z" level=info msg="-job init_networkdriver() = ERR (1)"
Jul 15 21:51:45 ubuntu docker[29723]: time="2015-07-15T21:51:45Z" level=fatal msg="Shutting down daemon due to errors: no such network interface"
Jul 15 21:51:45 ubuntu systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul 15 21:51:45 ubuntu systemd[1]: Unit docker.service entered failed state.
Jul 15 21:51:45 ubuntu systemd[1]: docker.service failed.
Jul 15 21:51:45 ubuntu kubelet[29715]: F0715 21:51:45.316816   29715 plugins.go:90] Couldn't init cloud provider "aws": error listing AWS instances: UnauthorizedOperation: You are not authorized to perform this operation.
Jul 15 21:51:45 ubuntu kubelet[29715]: status code: 403, request id: []
Jul 15 21:51:45 ubuntu systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Jul 15 21:51:45 ubuntu systemd[1]: Unit kubelet.service entered failed state.
Jul 15 21:51:45 ubuntu systemd[1]: kubelet.service failed.
Jul 15 21:51:45 ubuntu systemd[1]: kubelet.service holdoff time over, scheduling restart.
Jul 15 21:51:45 ubuntu systemd[1]: Started Kubernetes Kubelet Server.
Jul 15 21:51:45 ubuntu systemd[1]: Starting Kubernetes Kubelet Server...
Jul 15 21:51:45 ubuntu kubelet[29785]: I0715 21:51:45.634455   29785 server.go:271] Using root directory: /mnt/ephemeral/kubernetes/kubelet
Jul 15 21:51:45 ubuntu kubelet[29785]: I0715 21:51:45.635003   29785 manager.go:127] cAdvisor running in container: "/"
Jul 15 21:51:45 ubuntu kubelet[29785]: I0715 21:51:45.635774   29785 fs.go:93] Filesystem partitions: map[/dev/disk/by-uuid/ce99c711-e060-49c5-9633-9d4a92a96e43:{mountpoint:/ major:202 minor:1} /dev/mapper/vg--ephemeral-docker:{mountpoint:/mnt/ephemeral/docker major:252 minor:4} /dev/mapper/vg--ephemeral-kubernetes:{mountpoint:/mnt/ephemeral/kubernetes major:252 minor:5}]
Jul 15 21:51:45 ubuntu kubelet[29785]: I0715 21:51:45.638781   29785 manager.go:156] Machine: {NumCores:1 CpuFrequency:2494048 MemoryCapacity:3946217472 MachineID:2cbbdda5667a405fae66c42307efe2c4 SystemUUID:EC23ACBC-6F77-C4C1-6E06-6EDEBBC22DB4 BootID:df91a047-1eb0-4644-88d8-f8ed06c50b89 Filesystems:[{Device:/dev/disk/by-uuid/ce99c711-e060-49c5-9633-9d4a92a96e43 Capacity:8309932032} {Device:/dev/mapper/vg--ephemeral-docker Capacity:4135649280} {Device:/dev/mapper/vg--ephemeral-kubernetes Capacity:198902784}] DiskMap:map[252:5:{Name:dm-5 Major:252 Minor:5 Size:209715200 Scheduler:none} 202:0:{Name:xvda Major:202 Minor:0 Size:8589934592 Scheduler:deadline} 202:32:{Name:xvdc Major:202 Minor:32 Size:4289200128 Scheduler:deadline} 252:0:{Name:dm-0 Major:252 Minor:0 Size:4194304 Scheduler:none} 252:1:{Name:dm-1 Major:252 Minor:1 Size:4068474880 Scheduler:none} 252:2:{Name:dm-2 Major:252 Minor:2 Size:4068474880 Scheduler:none} 252:3:{Name:dm-3 Major:252 Minor:3 Size:4068474880 Scheduler:none} 252:4:{Name:dm-4 Major:252 Minor:4 Size:4269801472 Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:0a:ae:39:14:d3:23 Speed:0 Mtu:9001}] Topology:[{Id:0 Memory:3946217472 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:26214400 Type:Unified Level:3}]}]}
```

I think it boils down to the `no such network interface` error when starting up docker.

**Comment by frosenberg** [comment]
Looks like it is working now. I suspect it was the IAM role for the minion (b/c that is the only thing I clean up between the last `kube-up` run and this one). I had one laying around from a some older version that was different. I was not aware the the `kube-up.sh` does not update an "outdated" IAM role.

**Comment by justinsb** [comment]
Ah; thank you for noticing that.  There is indeed an issue where we don't verify the IAM role configuration.  My thinking here is that users may have deliberately granted more rights to their masters/minions.  Perhaps that is much rarer than the much-more-common case of us changing the IAM configuration.

kubelet restarts docker after it configures cbr0, so it sounds like that is why Docker was not starting when the IAM credentials were broken.

This is obviously not a great state-of-the-world; I will think about what we can do to make it better!

**Comment by frosenberg** [comment]
I'm closing this since this issue is resolved for me. Found another issue with DNS but I file a separate one.

**Comment by justinsb** [comment]
Thanks @frosenberg ; I opened #11373 because this has persuaded me that we should verify the IAM policy (because this was so unexpected).  I don't know if there is another issue that will come out of this around the fact that docker failed to start, but I think that may be "correct" (although surprising); we can't start docker till kubelet configures the network bridge.
