### ISSUE TITLE
transient json decoding error bringing up a cluster-- maybe hitting GCS timeout

### ISSUE THREAD

**Issue by amygdala** [GoogleCloudPlatform/kubernetes#1164]
I'm seeing this error transiently but fairly frequently. It seems to occur most often on the first attempt to bring a cluster up-- a retry will then go through.  Because of that, suspect a gcs-related timeout of some sort.

    % hack/dev-build-and-up.sh
    Building release tree
    Packaging release
    Building launch script
    Uploading to Google Storage
    CommandException: No URLs matched
    Traceback (most recent call last):
      File "hack/../release/make-public-gcs-acl.py", line 21, in <module>
        acl = json.load(sys.stdin)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
        **kw)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
        return _default_decoder.decode(s)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded
    Building the release failed!

**Comment by roberthbailey** [comment]
@amygdala - I'm sorry that we didn't address your issue in a timely manner. However, at this point, so much of the code base has changed since last september that it's probably not worth digging into this particular failure. If you are still seeing issues during cluster creation, please reopen this issue or create a new issue and we will do our best to help you out much more promptly.
