### ISSUE TITLE
Mysterious pod deploy error and cannot successfully debug

### ISSUE THREAD

**Issue by jasonkuhrt** [GoogleCloudPlatform/kubernetes#3286]
There is a 99.9999% chance I've made a mistake in trying to deploy a pod to my kubernetes cluster but I cannot figure out the problem. It is currently very hard to debug issues like this in Kubernetes.

I am using GKE which I believe is using Kubernetes 0.6.x?

Ok so my issue is that I've deployed a pod that looks like:

```yaml
# pod.yaml
kind: Pod
apiVersion: v1beta1
id: cloud-api-stream
labels:
  name: cloud-api-stream
desiredState:
  manifest:
    version: v1beta1
    id: cloud-api-stream
    containers:
      - name: cloud-api-stream
        image: quay.io/littlebits/cloud-server-api-stream
        ports:
          - name: cloud-api-stream
            containerPort: 7200
```

But once deployed it has this description:

```
$ kubectl --insecure-skip-tls-verify=true --server=https://x.x.x.x describe pod cloud-api-stream

Name:				cloud-api-stream
Image(s):			quay.io/littlebits/cloud-server-api-stream
Host:				k8s-cluster-test1-node-2.c.littlebits-electronics.internal/130.211.184.163
Labels:				name=cloud-api-stream
Status:				Failed
Replication Controllers:	<none>
No events.
```

Here are the last 100 lines of `kubelet` logs from node-2

```
jasonkuhrt@k8s-cluster-test1-node-2:~$ tail -n 100 /var/log/kubelet.log
E0107 21:13:57.231172 13487 etcd.go:71] Watch error: &{{  0001-01-01 00:00:00 +0000 UTC      map[]} Failure unexpected end of JSON input  <nil> 0}
I0107 21:13:58.231454 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:13:58.231531 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:13:58.231545 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false | method GET
I0107 21:13:58.233462 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:13:58.233494 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:13:58.233551 13487 logs.go:39] etcd DEBUG: watch /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:13:58.233569 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:13:58.233606 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=433
I0107 21:13:58.233620 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=433 | method GET
I0107 21:13:58.234455 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=433
I0107 21:18:58.234079 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=433
E0107 21:18:58.234183 13487 etcd.go:71] Watch error: &{{  0001-01-01 00:00:00 +0000 UTC      map[]} Failure unexpected end of JSON input  <nil> 0}
I0107 21:18:59.234458 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:18:59.234535 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:18:59.234547 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false | method GET
I0107 21:18:59.236467 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:18:59.236500 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:18:59.236542 13487 logs.go:39] etcd DEBUG: watch /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:18:59.236553 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:18:59.236579 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=433
I0107 21:18:59.236588 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=433 | method GET
I0107 21:18:59.237440 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=433
I0107 21:23:59.237098 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=433
E0107 21:23:59.237241 13487 etcd.go:71] Watch error: &{{  0001-01-01 00:00:00 +0000 UTC      map[]} Failure unexpected end of JSON input  <nil> 0}
I0107 21:24:00.237495 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:24:00.237572 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:24:00.237584 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false | method GET
I0107 21:24:00.239348 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:24:00.239383 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:24:00.239426 13487 logs.go:39] etcd DEBUG: watch /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:24:00.239436 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:24:00.239453 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=433
I0107 21:24:00.239468 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=433 | method GET
I0107 21:24:00.240291 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=433
I0107 21:24:16.661031 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=433
I0107 21:24:16.661256 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:24:16.661312 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
I0107 21:24:16.661326 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438 | method GET
I0107 21:24:16.673163 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
I0107 21:29:16.660706 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
E0107 21:29:16.660809 13487 etcd.go:71] Watch error: &{{  0001-01-01 00:00:00 +0000 UTC      map[]} Failure unexpected end of JSON input  <nil> 0}
I0107 21:29:17.661045 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:29:17.661125 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:29:17.661155 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false | method GET
I0107 21:29:17.662857 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:29:17.662884 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:29:17.662981 13487 logs.go:39] etcd DEBUG: watch /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:29:17.662995 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:29:17.663012 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
I0107 21:29:17.663021 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438 | method GET
I0107 21:29:17.665035 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
I0107 21:34:17.667082 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
E0107 21:34:17.667183 13487 etcd.go:71] Watch error: &{{  0001-01-01 00:00:00 +0000 UTC      map[]} Failure unexpected end of JSON input  <nil> 0}
I0107 21:34:18.667468 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:34:18.667541 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:34:18.667552 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false | method GET
I0107 21:34:18.681068 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:34:18.681127 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:34:18.681237 13487 logs.go:39] etcd DEBUG: watch /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:34:18.681249 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:34:18.681271 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
I0107 21:34:18.681281 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438 | method GET
I0107 21:34:18.690927 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
I0107 21:39:18.676113 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
E0107 21:39:18.676222 13487 etcd.go:71] Watch error: &{{  0001-01-01 00:00:00 +0000 UTC      map[]} Failure unexpected end of JSON input  <nil> 0}
I0107 21:39:19.676498 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:39:19.676573 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:39:19.676584 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false | method GET
I0107 21:39:19.678339 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:39:19.678535 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:39:19.678645 13487 logs.go:39] etcd DEBUG: watch /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:39:19.678657 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:39:19.678675 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
I0107 21:39:19.678690 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438 | method GET
I0107 21:39:19.681412 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
I0107 21:44:19.678962 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
E0107 21:44:19.679091 13487 etcd.go:71] Watch error: &{{  0001-01-01 00:00:00 +0000 UTC      map[]} Failure unexpected end of JSON input  <nil> 0}
I0107 21:44:20.679314 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:44:20.679388 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:44:20.679403 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false | method GET
I0107 21:44:20.681242 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:44:20.681270 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:44:20.681359 13487 logs.go:39] etcd DEBUG: watch /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:44:20.681396 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:44:20.681414 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
I0107 21:44:20.681424 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438 | method GET
I0107 21:44:20.683358 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
I0107 21:49:20.681707 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
E0107 21:49:20.681817 13487 etcd.go:71] Watch error: &{{  0001-01-01 00:00:00 +0000 UTC      map[]} Failure unexpected end of JSON input  <nil> 0}
I0107 21:49:21.682038 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:49:21.682120 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:49:21.682132 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false | method GET
I0107 21:49:21.702822 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:49:21.702870 13487 logs.go:39] etcd DEBUG: recv.success.http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&recursive=false&sorted=false
I0107 21:49:21.702980 13487 logs.go:39] etcd DEBUG: watch /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:49:21.702993 13487 logs.go:39] etcd DEBUG: get /registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet [http://10.240.65.178:4001]
I0107 21:49:21.703014 13487 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
I0107 21:49:21.703024 13487 logs.go:39] etcd DEBUG: send.request.to http://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438 | method GET
I0107 21:49:21.712337 13487 logs.go:39] etcd DEBUG: recv.response.fromhttp://10.240.65.178:4001/v2/keys/registry/hosts/k8s-cluster-test1-node-2.c.littlebits-electronics.internal/kubelet?consistent=true&wait=true&waitIndex=438
```

There is one other wrinkle. I realized earlier today that my error was that I did not provide a `.dockercfg` for `kubetet` for my image on `quay.io` that requires authentication. I knew this because I saw 403 errors in `kubelet` logs! I tried to fix this by placing a correct `.dockercfg` in each node's root `/` directory. Things still did not work. Then I realized that I need to (really?) restart the `kubelet` process via `sudo service kubelet restart`. After doing this however things have *still* not worked. All I see is that the `pod` `status` is "failed" and a whole bunch of not useful logs from `kubelet` (compared to before where I was at least about to figure out that it was failing on `quay.io` with `403`).

Thanks for your consideration!

**Comment by lavalamp** [comment]
I'm not sure why you don't see any events.

does ```kubectl logs <podname>``` print anything useful?

I think you'll have to do some grepping to find the relevant bits in your kubelet log-- I don't see anything out of the ordinary in the snippet you posted.

**Comment by jasonkuhrt** [comment]
@lavalamp `logs`? Do you mean `log`? And/but `log` needs `<podname>` `<container>`. So no I can't check that right now. Can you clarify? Different version of `kubectl`?

**Comment by lavalamp** [comment]
Yeah, log, sorry. I thought you didn't have to specify the container if there was only one. Just trying to figure out if this started and failed or never started.

Does your kubelet believe it is called "k8s-cluster-test1-node-2.c.littlebits-electronics.internal"? (Either ```$ hostname``` on the node must return that string, or ```$ ps aux|grep kubelet``` should contain that string after a hostname_override flag.)

**Comment by jasonkuhrt** [comment]
Oh, this is *maybe* interesting.

If I `ssh` back into the k8s node and try the container logs I see this:

```
$ sudo docker ps -a

CONTAINER ID        IMAGE                                               COMMAND               CREATED                  STATUS                          PORTS                    NAMES
92c364736b0f        quay.io/littlebits/cloud-server-api-stream:latest   "npm start"           Less than a second ago   Up Less than a second                                    k8s_cloud-api-stream.2fa388f5_cloud-api-stream.etcd_88ccbfc3-96b3-11e4-ac66-42010af041b2_ae4401942d
```
```
$ docker logs 92c364736b0f

2015/01/07 22:11:09 Get http:///var/run/docker.sock/v1.15/containers/92c364736b0f/json: dial unix /var/run/docker.sock: permission denied
```

**Comment by jasonkuhrt** [comment]
Wow... tired I guess. Here's the actually cmd result:

```
$ sudo docker logs 92c364736b0f

jasonkuhrt@k8s-cluster-test1-node-2:~$ sudo docker logs 408e7d45d52e

> cloud-server-api-stream@0.2.11 start /usr/src/app
> node lib/index

{"name":"app","hostname":"cloud-api-stream","pid":15,"component":"auth","level":30,"msg":"loaded","time":"2015-01-07T22:17:22.460Z","v":0}
{"name":"app","hostname":"cloud-api-stream","pid":15,"component":"wsserver","level":30,"config":{"oauth":{"auth_token_uri":"http://localhost:3000/access_tokens","auth_uri":"http://localhost:3000/oauth/authorize"},"port":7200,"log_level":"debug","cloudsetup_uri":"http://device-setup-local.littlebitscloud.cc:7000","api_http_uri":"http://localhost:8000","redis":{"database_number":1}},"msg":"Launching","time":"2015-01-07T22:17:22.812Z","v":0}

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.flush_and_error (/usr/src/app/node_modules/redis/index.js:142:13)
    at RedisClient.on_error (/usr/src/app/node_modules/redis/index.js:180:10)
    at Socket.<anonymous> (/usr/src/app/node_modules/redis/index.js:95:14)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)

npm ERR! Linux 3.16-0.bpo.2-amd64
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.16
npm ERR! code ELIFECYCLE
npm ERR! cloud-server-api-stream@0.2.11 start: `node lib/index`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the cloud-server-api-stream@0.2.11 start script 'node lib/index'.
npm ERR! This is most likely a problem with the cloud-server-api-stream package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/index
npm ERR! You can get their info via:
npm ERR!     npm owner ls cloud-server-api-stream
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

So here I see the logical application-level error! Great. Now, how can we make this way easier?

**Comment by lavalamp** [comment]
```kubectl log <podname>``` should have shown you that; if it didn't, there's a bug somewhere. (Or GKE is running too old of a version, but honestly I didn't think this was that new of a feature.)

**Comment by dchen1107** [comment]
Thanks for filing the issue. 

1) Kubernetes 0.6.x should have events from Kubelet. Have you ever tried cmd like:

kubectl get events | grep cloud-api-stream

I am wondering if there is a bug in kubectl describe path. 

2) kubectl log does require container name if there are more than one container in your pod. But the information you posted above should be provided by kubectl log. Also container name is a required field, unless you are starting your pod through a static config file, not through apiserver. 

3) We should surface the error causing by missed .dockercfg file.

**Comment by lavalamp** [comment]
Hm-- maybe it's possible that your kubelets don't support containerLogs.

**Comment by dchen1107** [comment]
@jasonkuhrt  From IRC,  you mentioned that you upgraded your cluster to a newer kubernetes release. After that, do you still observe the same issue here?

**Comment by jasonkuhrt** [comment]
@dchen1107 Good catch. Indeed this is working now! Should we close and assume it was because I had a `0.4.x` Kubernetes server running?

**Comment by lavalamp** [comment]
Ah, yes, that would explain it. Thanks for reporting back.
