### ISSUE TITLE
tons of stacktraces on query pod's stats in kubelet logs

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#3686]
Ran cluster with the latest code from HEAD, and kubelet logs fill with stacktraces as the belowing: cc/ @vishh

I0121 18:47:40.581867    4671 server.go:315] GET /stats/ccdac026-a107-11e4-a39d-42010af0c8cb/heapster?num_stats=9: (1.405045ms) 500
goroutine 21426 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc208123680, 0x1f4)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:182 +0x9c
net/http.Error(0x7fd4c7d51890, 0xc208123680, 0xc2081dde60, 0x8d, 0x1f4)
	/usr/src/go/src/pkg/net/http/server.go:1244 +0x96
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).error(0xc208154340, 0x7fd4c7d51890, 0xc208123680, 0x7fd4c7d431b0, 0xc208145cd0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:109 +0xf5
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).serveStats(0xc208154340, 0x7fd4c7d51890, 0xc208123680, 0xc2082652b0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:357 +0x367
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).handleStats(0xc208154340, 0x7fd4c7d51890, 0xc208123680, 0xc2082652b0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:241 +0x45
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.*Server.(github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.handleStats)·fm(0x7fd4c7d51890, 0xc208123680, 0xc2082652b0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:95 +0x44
net/http.HandlerFunc.ServeHTTP(0xc20815a2a0, 0x7fd4c7d51890, 0xc208123680, 0xc2082652b0)
	/usr/src/go/src/pkg/net/http/server.go:1235 +0x40
net/http.(*ServeMux).ServeHTTP(0xc2081102d0, 0x7fd4c7d51890, 0xc208123680, 0xc2082652b0)
	/usr/src/go/src/pkg/net/http/server.go:1511 +0x1a3
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).ServeHTTP(0xc208154320, 0x7fd4c7d51858, 0xc2080cc8c0, 0xc2082652b0)
	/go/src/github.com/GoogleCloudPlatform/kub

**Comment by dchen1107** [comment]
This issue affect heapster collecting resource usages for running pods.

**Comment by dchen1107** [comment]
Part of issue is caused by #3664, which cause cadvisor pod failure, and @thockin has a pending pr #3701 fixing it.

I also double checked, and the issue is NOT in release-v0.9.

**Comment by dchen1107** [comment]
I verified it with latest build, and #3701 fixed the issue. And now grafana dashboard works fine too.
