### ISSUE TITLE
kubelet fails to start with the --api_servers flag

### ISSUE THREAD

**Issue by kelseyhightower** [GoogleCloudPlatform/kubernetes#3899]
Kubernetes Version: 0.8.2

Kubelet config: 

```
/opt/bin/kubelet --address=0.0.0.0 --port=10250
--hostname_override=192.168.12.100 \
--api_servers=http://192.168.12.20:8080 \
 --logtostderr=true
```

Kubelet Logs:

```
Jan 28 22:25:56 node0 systemd[1]: Started Kubernetes Kubelet.
Jan 28 22:25:56 node0 kubelet[1134]: I0128 22:25:56.068549    1134 node.go:52] Connecting to docker on unix:///var/run/docker.sock
Jan 28 22:25:56 node0 kubelet[1134]: E0128 22:25:56.068810    1134 util.go:131] Unable to make apiserver client: stat : no such file or directory
Jan 28 22:25:56 node0 kubelet[1134]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 28 22:25:56 node0 kubelet[1134]: [signal 0xb code=0x1 addr=0x50 pc=0x5943e5]
Jan 28 22:25:56 node0 kubelet[1134]: goroutine 16 [running]:
Jan 28 22:25:56 node0 kubelet[1134]: runtime.panic(0x9e2220, 0xf47893)
Jan 28 22:25:56 node0 kubelet[1134]: /usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
Jan 28 22:25:56 node0 kubelet[1134]: github.com/coreos/go-etcd/etcd.(*Client).GetCluster(0x0, 0xc2080c6c30, 0x10, 0x4961fb)
Jan 28 22:25:56 node0 kubelet[1134]: /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client.go:284 +0x5
Jan 28 22:25:56 node0 kubelet[1134]: github.com/GoogleCloudPlatform/kubernetes/pkg/standalone.makePodSourceConfig(0xc20805a2c0, 0x10)
Jan 28 22:25:56 node0 kubelet[1134]: /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/standalone/standalone.go:205 +0x2a2
Jan 28 22:25:56 node0 kubelet[1134]: github.com/GoogleCloudPlatform/kubernetes/pkg/standalone.RunKubelet(0xc20805a2c0)
Jan 28 22:25:56 node0 kubelet[1134]: /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/standalone/standalone.go:164 +0xf3
Jan 28 22:25:56 node0 kubelet[1134]: main.main()
Jan 28 22:25:56 node0 kubelet[1134]: /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kubelet/kubelet.go:131 +0x530
Jan 28 22:25:56 node0 kubelet[1134]: goroutine 17 [runnable]:
Jan 28 22:25:56 node0 kubelet[1134]: runtime.MHeap_Scavenger()
Jan 28 22:25:56 node0 kubelet[1134]: /usr/src/go/src/pkg/runtime/mheap.c:507
Jan 28 22:25:56 node0 kubelet[1134]: runtime.goexit()
Jan 28 22:25:56 node0 kubelet[1134]: /usr/src/go/src/pkg/runtime/proc.c:1445
Jan 28 22:25:56 node0 kubelet[1134]: goroutine 18 [runnable]:
Jan 28 22:25:56 node0 kubelet[1134]: bgsweep()
Jan 28 22:25:56 node0 kubelet[1134]: /usr/src/go/src/pkg/runtime/mgc0.c:1976
Jan 28 22:25:56 node0 kubelet[1134]: runtime.goexit()
Jan 28 22:25:56 node0 kubelet[1134]: /usr/src/go/src/pkg/runtime/proc.c:1445
Jan 28 22:25:56 node0 kubelet[1134]: goroutine 19 [runnable]:
Jan 28 22:25:56 node0 kubelet[1134]: runfinq()
Jan 28 22:25:56 node0 kubelet[1134]: /usr/src/go/src/pkg/runtime/mgc0.c:2606
Jan 28 22:25:56 node0 kubelet[1134]: runtime.goexit()
Jan 28 22:25:56 node0 kubelet[1134]: /usr/src/go/src/pkg/runtime/proc.c:1445
Jan 28 22:25:56 node0 kubelet[1134]: goroutine 20 [runnable]:
Jan 28 22:25:56 node0 kubelet[1134]: github.com/golang/glog.(*loggingT).flushDaemon(0x10036c0)
Jan 28 22:25:56 node0 kubelet[1134]: /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:878
Jan 28 22:25:56 node0 kubelet[1134]: created by github.com/golang/glog.init<C2><B7>1
Jan 28 22:25:56 node0 kubelet[1134]: /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2b2
Jan 28 22:25:56 node0 kubelet[1134]: goroutine 17 [syscall]:
Jan 28 22:25:56 node0 kubelet[1134]: runtime.goexit()
Jan 28 22:25:56 node0 kubelet[1134]: /usr/src/go/src/pkg/runtime/proc.c:1445
Jan 28 22:25:56 node0 kubelet[1134]: goroutine 21 [runnable]:
Jan 28 22:25:56 node0 kubelet[1134]: github.com/GoogleCloudPlatform/kubernetes/pkg/watch.(*Broadcaster).loop(0xc208025020)
Jan 28 22:25:56 node0 kubelet[1134]: /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/watch/mux.go:105
Jan 28 22:25:56 node0 kubelet[1134]: created by github.com/GoogleCloudPlatform/kubernetes/pkg/watch.NewBroadcaster
Jan 28 22:25:56 node0 kubelet[1134]: /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/watch/mux.go:46 +0x9c
Jan 28 22:25:56 node0 kubelet[1134]: goroutine 22 [runnable]:
Jan 28 22:25:56 node0 kubelet[1134]: github.com/GoogleCloudPlatform/kubernetes/pkg/util.Forever(0xd2d7a0, 0x12a05f200)
Jan 28 22:25:56 node0 kubelet[1134]: /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:56
Jan 28 22:25:56 node0 kubelet[1134]: created by github.com/GoogleCloudPlatform/kubernetes/pkg/util.InitLogs
Jan 28 22:25:56 node0 kubelet[1134]: /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/logs.go:48 +0x9a
Jan 28 22:25:56 node0 kubelet[1134]: goroutine 23 [runnable]:
Jan 28 22:25:56 node0 kubelet[1134]: github.com/GoogleCloudPlatform/kubernetes/pkg/client/record.func<C2><B7>003()
Jan 28 22:25:56 node0 kubelet[1134]: /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/record/event.go:100
Jan 28 22:25:56 node0 kubelet[1134]: created by github.com/GoogleCloudPlatform/kubernetes/pkg/client/record.GetEvents
Jan 28 22:25:56 node0 systemd[1]: kube-kubelet.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 28 22:25:56 node0 systemd[1]: Unit kube-kubelet.service entered failed state.
Jan 28 22:25:56 node0 systemd[1]: kube-kubelet.service failed.
Jan 28 22:25:56 node0 kubelet[1134]: /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/record/event.go:115 +0xbc
```

**Comment by alex-mohr** [comment]
I think the problem stems from the lack of --etcd_servers flag?

From a GKE-launched VM:
% /usr/local/bin/kubelet -version
Kubernetes v0.8.1-dirty
% ps auxwww | grep kubelet
root      4944  0.5  0.7  97056 27468 ?        Sl   01:12   7:41 /usr/local/bin/kubelet -etcd_servers=http://10.240.226.175:4001 -api_servers=https://10.240.226.175:6443 -auth_path=/var/lib/kubelet/kubernetes_auth -address=0.0.0.0 -config=/etc/kubernetes/manifests --allow_privileged=False -v=2

From the stacktrace above, the panic seems to be in Jan 28 22:25:56 node0 kubelet[1134]: github.com/coreos/go-etcd/etcd.(*Client).GetCluster(0x0, 0xc2080c6c30, 0x10, 0x4961fb)?

Also, note I get a similar stacktrace just running "kubelet" w/o any args.

And for 0.9.2, GKE runs the following cmdline:
% /usr/local/bin/kubelet --etcd_servers=http://10.240.218.123:4001 --api_servers=https://10.240.218.123:6443 --auth_path=/var/lib/kubelet/kubernetes_auth --address=0.0.0.0 --config=/etc/kubernetes/manifests --allow_privileged=False --v=2 --cluster_dns=10.67.240.10 --cluster_domain=kubernetes.local

Although killing that kubelet and relaunching it w/o the --etcd_servers arg seems to work too.

@dchen1107 for kubelet?

**Comment by dchen1107** [comment]
ACK, looking into it now.

**Comment by dchen1107** [comment]
Ahh it is known issue, and fixed by #3356 initially. I patched 0.7 release. @filbranden later proposed a cleaner fix for this, but I guess he didn't patch 0.8 release with his fix.

**Comment by filbranden** [comment]
Yeah I never went back to release-0.8 to cherry-pick the fix... I imagine release-0.9 is also affected.

**Comment by dchen1107** [comment]
I will patch 0.8.2 with proper fix soon.

**Comment by kelseyhightower** [comment]
@dchen1107 Thanks for the fast response here.

**Comment by dchen1107** [comment]
@kelseyhightower I patched the release, and here is https://github.com/GoogleCloudPlatform/kubernetes/releases/tag/v0.8.4

I am closing the issue for now. If you still observe the problem, please re-open it. Thanks!
