### ISSUE TITLE
Periodic stack traces in kubelet logs

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#4717]
I haven't looked into the cause yet, but I've been seeing the following stack trace every 10 seconds in all of my kubelets' logs in both clusters that I've deployed from head today. I'll check it out tomorrow if no one else gets to it before me.

```
I0223 05:17:23.505930    4803 server.go:594] POST /stats/: (859.778µs) 500
goroutine 150 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc2081a5740, 0x1f4)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:188 +0x9a
net/http.Error(0x7ff2ee8914a0, 0xc2081a5740, 0xc208332b40, 0x47, 0x1f4)
        /usr/src/go/src/net/http/server.go:1274 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).error(0xc20806f8e0, 0x7ff2ee8914a0, 0xc2081a5740, 0x7ff2ee881a80, 0xc2082ec910)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:117 +0x124
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).serveStats(0xc20806f8e0, 0x7ff2ee8914a0, 0xc2081a5740, 0xc2083f4680)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:642 +0x6ff
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).handleStats(0xc20806f8e0, 0x7ff2ee8914a0, 0xc2081a5740, 0xc2083f4680)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:288 +0x46
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.*Server.(github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.handleStats)·fm(0x7ff2ee8914a0, 0xc2081a5740, 0xc2083f4680)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:101 +0x45
net/http.HandlerFunc.ServeHTTP(0xc2080f0430, 0x7ff2ee8914a0, 0xc2081a5740, 0xc2083f4680)
        /usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc2080eadb0, 0x7ff2ee8914a0, 0xc2081a5740, 0xc2083f4680)
        /usr/src/go/src/net/http/server.go:1541 +0x17d
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).ServeHTTP(0xc20806f8a0, 0x7ff2ee891468, 0xc208482e60, 0xc2083f4680)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_out
```

**Comment by vishh** [comment]
This must have been fixed on head now. Can you check @a-robinson?
In any case, I don't understand why kubelet dumps a stack trace in a loop.

**Comment by lavalamp** [comment]
This is not a crash. Kubelet is set to print a stack trace (as a debugging aid) whenever it returns an error to an HTTP request.

...Why is someone POSTing to /stats/? Shouldn't that be a URL one GETs?

**Comment by vishh** [comment]
The POST part is weird. AFAIK heapster is the only component that uses that
REST endpoint as of now and it does a GET.

**Comment by a-robinson** [comment]
Heapster does currently send post requests to kubelet for stats, although I don't know why: https://github.com/GoogleCloudPlatform/heapster/blob/master/sources/datasource/kubelet.go

**Comment by a-robinson** [comment]
Resolved in the corresponding [heapster issue](https://github.com/GoogleCloudPlatform/heapster/issues/127).
