### ISSUE TITLE
Cluster creation timing out

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#4975]
On GCE.

```
$ go run hack/e2e.go -v -up
2015/03/02 22:19:11 Running: get status
Project: kubernetes-satnam2
Zone: us-central1-b
current-context: "kubernetes-satnam2_kubernetes"
Running: /Users/satnam/gocode/src/github.com/GoogleCloudPlatform/kubernetes/cluster/../cluster/gce/../../_output/dockerized/bin/darwin/amd64/kubectl --match-server-version version
F0302 22:20:58.818724   26152 version.go:39] couldn't read version from server: Get https://130.211.121.12/version: dial tcp 130.211.121.12:443: i/o timeout
2015/03/02 22:20:58 Error running get status: exit status 255
2015/03/02 22:20:58 Running: up
Project: kubernetes-satnam2
Zone: us-central1-b
Starting cluster using provider: gce
... calling verify-prereqs
... calling kube-up
Project: kubernetes-satnam2
Zone: us-central1-b
Creating gs://kubernetes-staging-a2dc4
Creating gs://kubernetes-staging-a2dc4/...
Traceback (most recent call last):
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gsutil", line 22, in <module>
    gsutil.RunMain()
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gsutil.py", line 102, in RunMain
    sys.exit(gslib.__main__.main())
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 342, in main
    debug_level=debug, parallel_operations=parallel_operations)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 524, in _RunNamedCommandAndHandleExceptions
    debug_level, parallel_operations)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 272, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/commands/mb.py", line 171, in RunCommand
    metadata=bucket_metadata, provider=bucket_uri.scheme)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/cloud_api_delegator.py", line 187, in CreateBucket
    bucket_name, project_id=project_id, metadata=metadata, fields=fields)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/gcs_json_api.py", line 391, in CreateBucket
    global_params=global_params)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/third_party/storage_apitools/storage_v1_client.py", line 344, in Insert
    config, request, global_params=global_params)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/third_party/storage_apitools/base_api.py", line 588, in _RunMethod
    http, http_request, retries=self.__client.num_retries)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/third_party/storage_apitools/http_wrapper.py", line 291, in MakeRequest
    check_response_func=check_response_func)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/third_party/storage_apitools/http_wrapper.py", line 335, in _MakeRequestNoRetry
    redirections=redirections, connection_type=connection_type)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/client.py", line 545, in new_request
    redirections, connection_type)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1570, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1317, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1252, in _conn_request
    conn.connect()
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1018, in connect
    sock.connect((self.host, self.port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.timeout: timed out
2015/03/02 22:38:31 Error running up: exit status 1
2015/03/02 22:38:31 Error starting e2e cluster. Aborting.
exit status 1
satnam-macbookpro2:kubernetes satnam$ go run hack/e2e.go -v -up
2015/03/02 22:40:22 Running: get status
exit status 2
```
Trying again:
```
$ time go run hack/e2e.go -v -up
2015/03/02 22:40:34 Running: get status
Project: kubernetes-satnam2
Zone: us-central1-b
current-context: "kubernetes-satnam2_kubernetes"
Running: /Users/satnam/gocode/src/github.com/GoogleCloudPlatform/kubernetes/cluster/../cluster/gce/../../_output/dockerized/bin/darwin/amd64/kubectl --match-server-version version
F0302 22:42:20.883710   26626 version.go:39] couldn't read version from server: Get https://130.211.121.12/version: dial tcp 130.211.121.12:443: i/o timeout
2015/03/02 22:42:20 Error running get status: exit status 255
2015/03/02 22:42:20 Running: up
Project: kubernetes-satnam2
Zone: us-central1-b
Starting cluster using provider: gce
... calling verify-prereqs
... calling kube-up
Project: kubernetes-satnam2
Zone: us-central1-b
Creating gs://kubernetes-staging-a2dc4
Creating gs://kubernetes-staging-a2dc4/...
Traceback (most recent call last):
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gsutil", line 22, in <module>
    gsutil.RunMain()
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gsutil.py", line 102, in RunMain
    sys.exit(gslib.__main__.main())
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 342, in main
    debug_level=debug, parallel_operations=parallel_operations)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 524, in _RunNamedCommandAndHandleExceptions
    debug_level, parallel_operations)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 272, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/commands/mb.py", line 171, in RunCommand
    metadata=bucket_metadata, provider=bucket_uri.scheme)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/cloud_api_delegator.py", line 187, in CreateBucket
    bucket_name, project_id=project_id, metadata=metadata, fields=fields)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/gcs_json_api.py", line 391, in CreateBucket
    global_params=global_params)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/third_party/storage_apitools/storage_v1_client.py", line 344, in Insert
    config, request, global_params=global_params)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/third_party/storage_apitools/base_api.py", line 588, in _RunMethod
    http, http_request, retries=self.__client.num_retries)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/third_party/storage_apitools/http_wrapper.py", line 291, in MakeRequest
    check_response_func=check_response_func)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/gslib/third_party/storage_apitools/http_wrapper.py", line 335, in _MakeRequestNoRetry
    redirections=redirections, connection_type=connection_type)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/client.py", line 545, in new_request
    redirections, connection_type)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1570, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1317, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1252, in _conn_request
    conn.connect()
  File "/Users/satnam/google-cloud-sdk/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1018, in connect
    sock.connect((self.host, self.port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.timeout: timed out
2015/03/02 22:58:38 Error running up: exit status 1
2015/03/02 22:58:38 Error starting e2e cluster. Aborting.
exit status 1

real	18m4.023s
user	0m1.839s
sys	0m0.739s
```

**Comment by roberthbailey** [comment]
@a-robinson has also been looking into this.

**Comment by a-robinson** [comment]
I believe this is external to Kubernetes.

**Comment by a-robinson** [comment]
Sorry if that's a bit cryptic -- to be more specific, GCS has been a bit flaky tonight. If it's still a problem in the morning, reopen.

**Comment by SephVelut** [comment]
Getting the same problem and output.
