### ISSUE TITLE
Panic in kubectl running `kubectl label`

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#5074]
Reported [on the google-containers@ mailing list](https://groups.google.com/forum/#!topic/google-containers/vtfCcANGyCQ):

```
Hi all,

I'm following the instructions here to attach a label to a node.  The node currently doesn't have any labels and crashes when adding a label with ERROR: panic: assignment to entry in nil map.  Looking at pkg/kubectl/cmd/label.go, it seems that the combination of no labels and overwrite disabled causes the access to meta.Labels in validateNoOverwrites to fail.  I then tried adding the --overwrite flag when calling kubectl label nodes to bypass this and still had the same problem.  Any help would be appreciated!

Thanks,
Josh

Bonus dump:
$ gcloud preview container kubectl label --overwrite nodes k8s-example-node-1.c.e-sunlight-726.internal foo=bar
ERROR: panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd.labelFunc(0x7f9fd9f4c3c0, 0xc20809f0e0, 0xc208020101, 0xcd3660, 0x0, 0xc2080ddad0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/label.go:161 +0x234
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd.func·022(0x7f9fd9f4c3c0, 0xc20809f0e0, 0x0, 0x0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/label.go:76 +0x8f
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd.updateObject(0x7f9fd9f4e8d0, 0xc2080fc370, 0xc208087880, 0x9db450, 0x7, 0x7fffd13a0ce7, 0x2c, 0xc2080bfc88, 0x0, 0x0, ...)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/label.go:102 +0x13e
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd.func·023(0xc20809a6c0, 0xc2080942d0, 0x3, 0x9)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/label.go:79 +0x4b3
github.com/spf13/cobra.(*Command).execute(0xc20809a6c0, 0xc208092400, 0x9, 0x10, 0x0, 0x0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:383 +0x38d
github.com/spf13/cobra.(*Command).findAndExecute(0xc2080c8900, 0xc20800a010, 0xa, 0xa, 0x0, 0x0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:350 +0xd4
github.com/spf13/cobra.(*Command).Execute(0xc2080c8900, 0x0, 0x0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:436 +0xab3
main.main()
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kubectl/kubectl.go:27 +0x81

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xcc9e60)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [syscall]:
os/signal.loop()
        /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 10 [runnable]:
net/http.(*persistConn).readLoop(0xc2081320b0)
        /usr/src/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
        /usr/src/go/src/net/http/transport.go:660 +0xc9f

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc2081320b0)
        /usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/src/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by a-robinson** [comment]
Looks like this was a bug in 0.11.0, but should be fixed in 0.12.0 due to #4311.
