### ISSUE TITLE
Frontend cannot connect to redis data-base in guestbook example.

### ISSUE THREAD

**Issue by piosz** [GoogleCloudPlatform/kubernetes#5091]
It comes up in the new guestbook.sh e2e test (#3693). I'll try to reproduce manually.

```
<br /> <b>Fatal error</b>: Uncaught exception 'Predis\Connection\ConnectionException' with message 'Error while reading line from the server [tcp://10.0.211.28:6379]' in /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php:141 Stack trace:
#0 /vendor/predis/predis/lib/Predis/Connection/StreamConnection.php(208): Predis\Connection\AbstractConnection-&gt;onConnectionError('Error while rea...')
#1 /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php(130): Predis\Connection\StreamConnection-&gt;read()
#2 /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php(122): Predis\Connection\AbstractConnection-&gt;readResponse(Object(Predis\Command\StringGet))
#3 /vendor/predis/predis/lib/Predis/Client.php(246): Predis\Connection\AbstractConnection-&gt;executeCommand(Object(Predis\Command\StringGet))
#4 /vendor/predis/predis/lib/Predis/Client.php(228): Predis\Client-&gt;executeCommand(Object(Predis\Command\StringGet))
#5 /app/index.php(32): Predis\Client-&gt;__call('get', Array)
#6 /app/index.php(32): Predis\Client-&gt;get('messag in <b>/vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php</b> on line <b>141</b><br />```

**Comment by piosz** [comment]
Reproduced in my own cluster:

```
pszczesniak@piosz:~/git/kubernetes$ ./cluster/kubectl.sh create -f examples/guestbook/
current-context: "tidal-shield-848_kubernetes"
Running: ./cluster/../cluster/gce/../../_output/local/bin/linux/amd64/kubectl create -f examples/guestbook/
frontend-controller
frontend
redis-master-controller
redis-master
redis-slave-controller
redisslave
pszczesniak@piosz:~/git/kubernetes$ ./cluster/kubectl.sh get services frontend -o json
current-context: "tidal-shield-848_kubernetes"
Running: ./cluster/../cluster/gce/../../_output/local/bin/linux/amd64/kubectl get services frontend -o json
{
    "kind": "Service",
    "id": "frontend",
    "uid": "ec64398f-c342-11e4-b4a3-42010af08af6",
    "creationTimestamp": "2015-03-05T14:21:32Z",
    "selfLink": "/api/v1beta1/services/frontend?namespace=default",
    "resourceVersion": 68039,
    "apiVersion": "v1beta1",
    "namespace": "default",
    "port": 8000,
    "protocol": "TCP",
    "labels": {
        "name": "frontend"
    },
    "selector": {
        "name": "frontend"
    },
    "createExternalLoadBalancer": true,
    "publicIPs": [
        "104.154.37.133"
    ],
    "containerPort": "http-server",
    "portalIP": "10.0.171.36",
    "sessionAffinity": "None"
}
pszczesniak@piosz:~/git/kubernetes$ curl 104.154.37.133:8000/index.php?cmd=get\&key=messages
<br />
<b>Fatal error</b>:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'Connection timed out [tcp://10.0.144.100:6379]' in /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php:141
Stack trace:
#0 /vendor/predis/predis/lib/Predis/Connection/StreamConnection.php(96): Predis\Connection\AbstractConnection-&gt;onConnectionError('Connection time...', 110)
#1 /vendor/predis/predis/lib/Predis/Connection/StreamConnection.php(70): Predis\Connection\StreamConnection-&gt;tcpStreamInitializer(Object(Predis\Connection\ConnectionParameters))
#2 /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php(96): Predis\Connection\StreamConnection-&gt;createResource()
#3 /vendor/predis/predis/lib/Predis/Connection/StreamConnection.php(144): Predis\Connection\AbstractConnection-&gt;connect()
#4 /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php(181): Predis\Connection\StreamConnection-&gt;connect()
#5 /vendor/predis/predis/lib/Predis/Connection/StreamConnection.php(183): Predis\Connection\AbstractConnection in <b>/vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php</b> on line <b>141</b><br />
```

Am I doing anthing wrong?

**Comment by piosz** [comment]
Also the same stuff from browser. While I'm clicking Submit I can see:

![screen shot 2015-03-05 at 3 25 07 pm](https://cloud.githubusercontent.com/assets/10819974/6506681/18f0a686-c34d-11e4-8fde-eaad0023ada0.png)

**Comment by piosz** [comment]
This may be related to #4914

**Comment by piosz** [comment]
The problem is that when frontend pods are created, information about redis services may not be propagated yet. I'll change guestbook example to use SkyDNS instead of host:port.

**Comment by piosz** [comment]
@brendandburns what do you think about using kube-dns instead of host:port in guestbook example. Please notice that kube-dns is not yet reliable #5181

**Comment by mulloymorrow** [comment]
HAProxy might be helpful here: https://robertianhawdon.me.uk/2014/02/11/sysops-installing-a-high-availability-redis-service-on-centos-6-x-in-windows-azure/

**Comment by mulloymorrow** [comment]
https://github.com/mikedanese/k8s-haproxy/commits?author=mikedanese

**Comment by piosz** [comment]
It's actually not related. The problem was not with redis itself but with distributing redis address over containers.
