### ISSUE TITLE
Heapster is sending the wrong field selector.

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#5202]
```
errors.go:66] apiserver received an error that is not an api.Status: field label not supported: Status.Host
I0309 21:53:47.251421   10193 handlers.go:109] GET /api/v1beta1/pods?fields=Status.Host%21%3D&namespace=: (690.229µs) 500
goroutine 1696 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc208968c60, 0x1f4)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:188 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7f92879af358, 0xc20801d260, 0x7f92879af520, 0xc20892f280, 0x7f92879cda18, 0xc208968c60)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:248 +0x232
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.errorJSON(0x7f92879aab80, 0xc208918ad0, 0x7f92879af358, 0xc20801d260, 0x7f92879cda18, 0xc208968c60, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:255 +0xa3
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·017(0xc208a571d0, 0xc2088dfbd0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:120 +0x31f
github.com/emicklei/go-restful.func·005(0xc208a571d0, 0xc2088dfbd0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:192 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc208a57260, 0xc208a571d0, 0xc2088dfbd0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·003(0xc208a571d0, 0xc2088dfbd0, 0xc208a57260)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:82 +0x7f
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc208a57260, 0xc208a571d0, 0xc2088dfbd0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-r
```

@nikhiljindal

**Comment by nikhiljindal** [comment]
We now require users to specify versioned fields in field selectors.
There is no Status field in v1beta1 pods struct (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta1/types.go#L510).

`GET /api/v1beta1/pods?fields=Status.Host%21%3D&namespace=:` needs to be changed to
`GET /api/v1beta1/pods?fields=DesiredState.Host%21%3D&namespace=:`

**Comment by brendandburns** [comment]
ok, well then we need to update the Scheduler.  I'm 99% certain that's where it is coming from.

**Comment by nikhiljindal** [comment]
I did update the scheduler (https://github.com/GoogleCloudPlatform/kubernetes/pull/4575/) to make e2e tests pass.
Let me have another look.

Can you please provide steps to repro?

**Comment by brendandburns** [comment]
Ok, I dug down deeper.  These errors are surfacing from Heapster, which is old and now doing the wrong thing.

@vishh we need to fix this.

Also, why is the monitoring e2e test still passing?

**Comment by vishh** [comment]
Ack. I will fix this and make a new release soon. I will probe into the e2e test behavior as well.

**Comment by nikhiljindal** [comment]
FYI, there might be a few more changes coming to field selectors: https://github.com/GoogleCloudPlatform/kubernetes/issues/5206 and https://github.com/GoogleCloudPlatform/kubernetes/issues/5207

**Comment by vishh** [comment]
Thanks for the pointers @nikhiljindal. This issue has been fixed on heapster. Tested with a cluster build from HEAD and I don't see the stack traces on api server.
