### ISSUE TITLE
Failure to delete load balancer causes apiserver crash

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#5374]
```
I0310 20:16:36.091506   14883 handlers.go:109] GET /api/v1beta1/endpoints/service-20588?namespace=default: (860.851µs) 200
I0310 20:16:36.240189   14883 handlers.go:109] PUT /api/v1beta1/endpoints/service-20588?namespace=default: (147.945199ms) 200
W0310 20:16:37.512163   14883 gce.go:286] Failed to delete Target Pool %s, got error %s. e2e-test-beeps-default-frontend googleapi: Error 404: The resource 'projects/kubernetesdevgce/regions/us-central1/targetPools/e2e-test-beeps-default-frontend' was not found, notFound
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4cfbb5]

goroutine 18193 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/gce.(*GCECloud).waitForRegionOp(0xc208154e40, 0x0, 0xc20817694c, 0xb, 0x0, 0x0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/gce/gce.go:191 +0x4b5
github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/gce.(*GCECloud).DeleteTCPLoadBalancer(0xc208154e40, 0xc20873bfc0, 0x1f, 0xc20817694c, 0xb, 0x0, 0x0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/gce/gce.go:288 +0xa4d
github.com/GoogleCloudPlatform/kubernetes/pkg/registry/service.(*REST).deleteExternalLoadBalancer(0xc2081e6f50, 0x7fdf536b4490, 0xc20850c2a0, 0xc208b98f00, 0x0, 0x0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/registry/service/rest.go:304 +0x249
github.com/GoogleCloudPlatform/kubernetes/pkg/registry/service.(*REST).Delete(0xc2081e6f50, 0x7fdf536b4490, 0xc20850c2a0, 0xc20889065d, 0x8, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/registry/service/rest.go:141 +0x1b7
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·022(0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:288 +0x80
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·024()
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:328 +0x38
created by github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.finishRequest
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:333 +0x1e4
```

**Comment by piosz** [comment]
Seems to be fixed.
