### ISSUE TITLE
kube-up for GCE repeatedly fails

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#5487]
I've wasted an insane numer of hours over this. Note also that date gives an error for an illegal "-I" flag and there is an unbound variable error. This is running on my Macbook Pro.

```
$ cluster/kube-up.sh
Starting cluster using provider: gce
... calling verify-prereqs
... calling kube-up
Project: kubernetes-satnam2
Zone: us-central1-b
current-context: "kubernetes-satnam2_kubernetes/"
Running: cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/darwin/amd64/kubectl config view -o template --template={{$root := .}}{{with index $root "current-context"}}{{with index $root "contexts" .}}{{with index . "user"}}{{with index $root "users" .}}{{index . "username"}}{{end}}{{end}}{{end}}{{end}}
current-context: "kubernetes-satnam2_kubernetes/"
Running: cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/darwin/amd64/kubectl config view -o template --template={{$root := .}}{{with index $root "current-context"}}{{with index $root "contexts" .}}{{with index . "user"}}{{with index $root "users" .}}{{index . "password"}}{{end}}{{end}}{{end}}{{end}}
+++ Staging server tars to Google Storage: gs://kubernetes-staging-a2dc4/devel
Starting master and configuring firewalls
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#pdperformance.
Created [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/zones/us-central1-b/disks/kubernetes-master-pd].
NAME                 ZONE          SIZE_GB TYPE        STATUS
kubernetes-master-pd us-central1-b 10      pd-standard READY
date: illegal option -- I
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
cluster/../cluster/gce/util.sh: line 422: @: unbound variable
+++ Logging using Fluentd to elasticsearch
Created [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/global/firewalls/kubernetes-master-https].
NAME                    NETWORK SRC_RANGES RULES   SRC_TAGS TARGET_TAGS
kubernetes-master-https default 0.0.0.0/0  tcp:443          kubernetes-master
Created [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/global/firewalls/kubernetes-minion-all].
NAME                  NETWORK SRC_RANGES    RULES                    SRC_TAGS TARGET_TAGS
kubernetes-minion-all default 10.244.0.0/16 tcp,udp,icmp,esp,ah,sctp          kubernetes-minion
Created [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/zones/us-central1-b/instances/kubernetes-master].
NAME              ZONE          MACHINE_TYPE  INTERNAL_IP    EXTERNAL_IP   STATUS
kubernetes-master us-central1-b n1-standard-1 10.240.144.197 104.197.4.178 RUNNING
Updated [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/zones/us-central1-b/instances/kubernetes-master].
Creating minions.
date: illegal option -- I
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
cluster/../cluster/gce/util.sh: line 422: @: unbound variable
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#pdperformance.
Created [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/global/instanceTemplates/kubernetes-minion-template].
NAME                       MACHINE_TYPE  CREATION_TIMESTAMP
kubernetes-minion-template n1-standard-1 2015-03-14T13:42:41.937-07:00
Managed instance group kubernetes-minion-group is being created. Operation: operation-1426365766785-46c55cca-d299-42f5-a919-f21811d0b3c7
Waiting for minions to run. 0 out of 4 running. Retrying.
Waiting for minions to run. 0 out of 4 running. Retrying.
Waiting for minions to run. 0 out of 4 running. Retrying.
Waiting for minions to run. 0 out of 4 running. Retrying.
Waiting for minions to run. 0 out of 4 running. Retrying.
Waiting for minions to run. 0 out of 4 running. Retrying.
Waiting for minions to run. 1 out of 4 running. Retrying.
Waiting for minions to run. 1 out of 4 running. Retrying.
Waiting for minions to run. 2 out of 4 running. Retrying.
Waiting for minions to run. 3 out of 4 running. Retrying.
MINION_NAMES=kubernetes-minion-5bb4 kubernetes-minion-b1z7 kubernetes-minion-c1ko kubernetes-minion-ns8g
Updated [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/zones/us-central1-b/instances/kubernetes-master].
Updated [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/zones/us-central1-b/instances/kubernetes-minion-b1z7].
Updated [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/zones/us-central1-b/instances/kubernetes-minion-ns8g].
Updated [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/zones/us-central1-b/instances/kubernetes-minion-5bb4].
Updated [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/zones/us-central1-b/instances/kubernetes-minion-c1ko].
Created [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/global/routes/kubernetes-minion-b1z7].
Created [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/global/routes/kubernetes-minion-5bb4].
Created [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/global/routes/kubernetes-minion-c1ko].
Created [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/global/routes/kubernetes-master].
Created [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/global/routes/kubernetes-minion-ns8g].
NAME                   NETWORK DEST_RANGE    NEXT_HOP                                       PRIORITY
kubernetes-minion-b1z7 default 10.244.1.0/24 us-central1-b/instances/kubernetes-minion-b1z7 1000
NAME                   NETWORK DEST_RANGE    NEXT_HOP                                       PRIORITY
NAME              NETWORK DEST_RANGE    NEXT_HOP                                  PRIORITY
kubernetes-minion-ns8g default 10.244.3.0/24 us-central1-b/instances/kubernetes-minion-ns8g 1000
kubernetes-master default 10.246.0.0/24 us-central1-b/instances/kubernetes-master 1000
NAME                   NETWORK DEST_RANGE    NEXT_HOP                                       PRIORITY
kubernetes-minion-c1ko default 10.244.2.0/24 us-central1-b/instances/kubernetes-minion-c1ko 1000
NAME                   NETWORK DEST_RANGE    NEXT_HOP                                       PRIORITY
kubernetes-minion-5bb4 default 10.244.0.0/24 us-central1-b/instances/kubernetes-minion-5bb4 1000
Using master: kubernetes-master (external IP: 104.197.4.178)
Created [https://www.googleapis.com/compute/v1/projects/kubernetes-satnam2/regions/us-central1/addresses/kubernetes-master-ip].
NAME                 REGION      ADDRESS       STATUS
kubernetes-master-ip us-central1 104.197.4.178 IN_USE
Waiting for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start
  up.

Kubernetes cluster created.

current-context: "kubernetes-satnam2_kubernetes/"
Running: cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/darwin/amd64/kubectl config set-cluster kubernetes-satnam2_kubernetes --server=https://104.197.4.178 --certificate-authority=/tmp/kubernetes.ca.crt --embed-certs=true
current-context: "kubernetes-satnam2_kubernetes/"
Running: cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/darwin/amd64/kubectl config set-credentials kubernetes-satnam2_kubernetes --username=admin --password=LNDt9uxjH13F1q9f --client-certificate=/tmp/kubecfg.crt --client-key=/tmp/kubecfg.key --embed-certs=true
current-context: "kubernetes-satnam2_kubernetes/"
Running: cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/darwin/amd64/kubectl config set-context kubernetes-satnam2_kubernetes --cluster=kubernetes-satnam2_kubernetes --user=kubernetes-satnam2_kubernetes
current-context: "kubernetes-satnam2_kubernetes/"
Running: cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/darwin/amd64/kubectl config use-context kubernetes-satnam2_kubernetes --cluster=kubernetes-satnam2_kubernetes
Wrote config for kubernetes-satnam2_kubernetes to /Users/satnam/.kube/.kubeconfig
Sanity checking cluster...
Attempt 1 to check Docker on node kubernetes-minion-5bb4 ... [working]
Attempt 1 to check Docker on node kubernetes-minion-b1z7 ... [working]
Attempt 1 to check Docker on node kubernetes-minion-c1ko ... [working]
Attempt 1 to check Docker on node kubernetes-minion-ns8g ... [working]

Kubernetes cluster is running.  The master is running at:

  https://104.197.4.178

The user name and password to use is located in /Users/satnam/.kube/.kubeconfig.

... calling validate-cluster
current-context: "kubernetes-satnam2_kubernetes"
Running: cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/darwin/amd64/kubectl config view -o template --template={{$root := .}}{{with index $root "current-context"}}{{with index $root "contexts" .}}{{with index . "user"}}{{with index $root "users" .}}{{index . "username"}}{{end}}{{end}}{{end}}{{end}}
current-context: "kubernetes-satnam2_kubernetes"
Running: cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/darwin/amd64/kubectl config view -o template --template={{$root := .}}{{with index $root "current-context"}}{{with index $root "contexts" .}}{{with index . "user"}}{{with index $root "users" .}}{{index . "password"}}{{end}}{{end}}{{end}}{{end}}
Project: kubernetes-satnam2
Zone: us-central1-b
Traceback (most recent call last):
  File "/Users/satnam/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 204, in <module>
    main()
  File "/Users/satnam/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 200, in main
    _cli.Execute()
  File "/Users/satnam/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 558, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/satnam/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1004, in Run
    last_group = context_filter(tool_context, Http, args)
  File "/Users/satnam/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 407, in ContextFilter
    group.Filter(context, args)
  File "/Users/satnam/google-cloud-sdk/./lib/googlecloudsdk/calliope/exceptions.py", line 86, in TryFunc
    return func(*args, **kwargs)
  File "/Users/satnam/google-cloud-sdk/lib/googlecloudsdk/preview/commands/instance_groups/__init__.py", line 56, in Filter
    discoveryServiceUrl=discovery_url)
  File "/Users/satnam/google-cloud-sdk/./lib/oauth2client/util.py", line 129, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/satnam/google-cloud-sdk/./lib/apiclient/discovery.py", line 198, in build
    resp, content = http.request(requested_url)
  File "/Users/satnam/google-cloud-sdk/./lib/googlecloudsdk/core/cli.py", line 180, in RequestWithErrHandling
    return orig_request(*args, **kwargs)
  File "/Users/satnam/google-cloud-sdk/./lib/oauth2client/util.py", line 129, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/satnam/google-cloud-sdk/./lib/oauth2client/client.py", line 533, in new_request
    redirections, connection_type)
  File "/Users/satnam/google-cloud-sdk/./lib/googlecloudsdk/core/cli.py", line 149, in RequestWithUserAgentAndTracing
    return orig_request(*modified_args, **kwargs)
  File "/Users/satnam/google-cloud-sdk/./lib/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/satnam/google-cloud-sdk/./lib/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/satnam/google-cloud-sdk/./lib/httplib2/__init__.py", line 1306, in _conn_request
    response = conn.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1033, in getresponse
    raise ResponseNotReady()
httplib.ResponseNotReady
```

**Comment by roberthbailey** [comment]
Not that it helps too much, but it looks to me like its failing when trying to get a list of the minion names as part of validate-cluster.sh: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/util.sh#L152

Can you run this command by hand?

```gcloud preview --project "${PROJECT}" instance-groups \
    --zone "${ZONE}" instances --group "${NODE_INSTANCE_PREFIX}-group" list \
    | cut -d'/' -f11```

**Comment by satnam6502** [comment]
I tried:
```
 4 gcloud preview --project kubernetes-satnam2 instance-groups --zone us-central1-b instances --group kubernetes-group list | cut -d'/' -f11
ERROR: (gcloud.preview.instance-groups.instances.list) ResponseError: code=404, message=The view '(,us-central1-b,kubernetes-satnam2,kubernetes-group)' was not found.
```
but perhaps I got something wrong (will look again when I have more time).

**Comment by zmerlynn** [comment]
Is your gcloud up to date? I realize that I actually have a crontab to
update it.

**Comment by zmerlynn** [comment]
(I'm not claiming it would matter, but I've had no reliability issues.)

**Comment by satnam6502** [comment]
Yes, it is. Let me come back to this on Monday. This is for Cinderella.

**Comment by satnam6502** [comment]
I am going to delete every cluster I have and then rm -rf my .kube directory and hope that a fresh start looks more kindly down on me. @jlowdermilk

**Comment by alex-mohr** [comment]
@satnam6502 ... did it work?  Sorry for the issues!

**Comment by satnam6502** [comment]
Yes, it now works. For each cluster I had to manually delete the e2e network and then it started to work.
