### ISSUE TITLE
ubuntu_cluster: Can't dermine redis-master's ip in guestbook example

### ISSUE THREAD

**Issue by decker502** [GoogleCloudPlatform/kubernetes#5747]
I followed the guestbook  guide and encountered below problem:

k8s version: release 0.13

# Curl test

````

root@uminion:~# curl "192.168.40.11:8000/index.php?cmd=set&key=messages&value=jay_sais_hi"
<br />
<b>Fatal error</b>:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://redis-master:6379]' in /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php:141
Stack trace:
#0 /vendor/predis/predis/lib/Predis/Connection/StreamConnection.php(96): Predis\Connection\AbstractConnection-&gt;onConnectionError('php_network_get...', 0)
#1 /vendor/predis/predis/lib/Predis/Connection/StreamConnection.php(70): Predis\Connection\StreamConnection-&gt;tcpStreamInitializer(Object(Predis\Connection\ConnectionParameters))
#2 /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php(96): Predis\Connection\StreamConnection-&gt;createResource()
#3 /vendor/predis/predis/lib/Predis/Connection/StreamConnection.php(144): Predis\Connection\AbstractConnection-&gt;connect()
#4 /vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php(181): Predis\Connection\StreamConnection-&gt;connect()
#5 /vendor/predis/predis/lib/Predis/Connection/StreamConnecti in <b>/vendor/predis/predis/lib/Predis/Connection/AbstractConnection.php</b> on line <b>141</b><br />

````

I don't know why they are there.

# Flannel IP

Flannel's IP is same in all minions, Is that all right?

**Comment by roberthbailey** [comment]
@jainvipin is listed as the ubuntu maintainer in MAINTAINERS.md so maybe he can help.

**Comment by jainvipin** [comment]
@decker502 
Flannel's IP (flannel0) shouldn't be on all the minions. If flannel is unable to acquire a subnet it can run into this issue. Can you send the output of '/run/flannel/subnet.env' on from the machines, that shows same flannel's IP? 

I did run into one problem with the ubuntu-cluster script, configure.sh; I will submit a PR for the same. To see if that's the problem you are running into, can you please confirm:
- Did you use configure.sh to configure the master/minion IPs?
- if 'kubectl get minions' is showing all minions in `Ready` state?

**Comment by decker502** [comment]
@jainvipin Two problems can all be confirmed. 

* I use configure.sh.
* KUBECTL command is showing **Read** state.

I had fixed Flannel problem. Because my cluster is built by vagrant, eth0's IP is 10.0.2.15. Unfortunately Flannel use this IP. When I assign iface param , it's solved.

**Comment by jainvipin** [comment]
@decker502 - thanks. 
If you fixed flannel problem, ping to flannel0's IP from various nodes would be working.

I also assume you mean *Ready* state above in kubectl command. 

Did you reconfigure Docker, using reconfigureDocker.sh?
Is the bip used by Docker matching up to whatever flannel is using i.e. `--bip=${FLANNEL_SUBNET}` is used as option in docker deamon?

Can you also confirm the output of the command `kubectl exec -p <pod-name> -c <container-name> -- ifconfig -a` output for redis-master to confirm that that IP obtained by the container is indeed in the proper range. If that shows okay you can further execute ping using `kubectl exec -p <pod-name> -c <container-name> -- ping <redis-slave-ip>`

Perhaps I can get some command outputs from you offline.

**Comment by decker502** [comment]
@jainvipin 
Yes,  ping to flannel0's IP is working.

I had reconfigure  Docker, using reconfigureDocker.sh.

The bip is used  by Docker matching up to whatever flannel is using.

````

 /usr/bin/docker -d -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock --bip=10.0.67.1/24 --mtu=1472

````

````
root@umaster:/opt# kubectl exec -p redis-master-controller-fplln -c redis-master -- ifconfig -a
eth0      Link encap:Ethernet  HWaddr 02:42:0a:00:43:02  
          inet addr:10.0.67.2  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::42:aff:fe00:4302/64 Scope:Link
          UP BROADCAST RUNNING  MTU:1472  Metric:1
          RX packets:16 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1296 (1.2 KB)  TX bytes:648 (648.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
````

````
root@umaster:/opt# kubectl exec -p redis-master-controller-fplln -c redis-master -- ping 10.0.83.2
PING 10.0.83.2 (10.0.83.2) 56(84) bytes of data.
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.67 ms
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=2.22 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=2.27 ms (DUP!)
````

It is right to connect the IP , but redis-slave container can't resolve **redis-master** .
 Redis master's IP is determined by container's ENV when K8S's version was 0.12 . I don't known how container resolve the name when version is 0.13.

**Comment by jainvipin** [comment]
@decker502 - ah, the ip connectivity seem okay; DUP seems like an issue, because if some other container is also owning this IP, a reliable connection can not be established. Can you examine all other containers and see if any other container is also given the IP address same as that of redis-master i.e. 10.0.83.2? That could be a problem, based on the above debug logs.

I am also not sure how do you conclude that this is a problem with 0.13 and name resolution?

ping @erictune, @WIZARD-CXY, @resouer as they merged/worked one of the problems with configure.sh in #5245

**Comment by decker502** [comment]
May the below info be useful.

````
root@umaster:/opt# kubectl get pods
POD                             IP                  CONTAINER(S)        IMAGE(S)                    HOST                          LABELS                                         STATUS              CREATED
redis-master-controller-fplln   10.0.67.2           redis-master        dockerfile/redis            192.168.40.13/192.168.40.13   app=redis,name=redis-master                    Running             2 hours
redis-slave-controller-gziey    10.0.83.2           redis-slave         kubernetes/redis-slave:v2   192.168.40.12/192.168.40.12   app=redis,name=redis-slave,uses=redis-master   Running             2 hours
````

````
root@umaster:/opt# kubectl exec -p redis-master-controller-fplln -c redis-master -- ifconfig -a
eth0      Link encap:Ethernet  HWaddr 02:42:0a:00:43:02  
          inet addr:10.0.67.2  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::42:aff:fe00:4302/64 Scope:Link
          UP BROADCAST RUNNING  MTU:1472  Metric:1
          RX packets:1091 errors:0 dropped:0 overruns:0 frame:0
          TX packets:78 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:106478 (106.4 KB)  TX bytes:7340 (7.3 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
````
````
root@umaster:/opt# kubectl exec -p redis-slave-controller-gziey -c redis-slave -- ifconfig -a
eth0      Link encap:Ethernet  HWaddr 02:42:0a:00:53:02  
          inet addr:10.0.83.2  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::42:aff:fe00:5302/64 Scope:Link
          UP BROADCAST RUNNING  MTU:1472  Metric:1
          RX packets:314 errors:0 dropped:0 overruns:0 frame:0
          TX packets:309 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:30822 (30.8 KB)  TX bytes:29114 (29.1 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
····

**Comment by jainvipin** [comment]
@decker502 - this info is more or less same as what you sent earlier
Do you know how many DUPs responses do you get for the ping request? Do you ever get ping response for sequences other than 1? This would tell if there is a loop somewhere or containers with duplicate IPs.
`docker ps` on both systems would also help understand if something else is running or not.

**Comment by WIZARD-CXY** [comment]
I agreed with @jainvipin .You can solve the dup error first.I think it maybe a static route problem. You can check the env variables in docker container using docker inspect on the minion node or checking the kubelet log.
You can also check the kube-proxy log on redis-slave node to see if there are some hints help debugging.

**Comment by decker502** [comment]
* Ping
````
root@umaster:/opt# kubectl exec -p redis-master-controller-fplln -c redis-master -- ping 10.0.83.2
PING 10.0.83.2 (10.0.83.2) 56(84) bytes of data.
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.04 ms
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.20 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.23 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.43 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.46 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.50 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.53 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.55 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.58 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.60 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.63 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.65 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.69 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.72 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.75 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=1 ttl=60 time=1.78 ms (DUP!)
64 bytes from 10.0.83.2: icmp_seq=2 ttl=60 time=1.42 ms
64 bytes from 10.0.83.2: icmp_seq=2 ttl=60 time=1.47 ms (DUP!)
````

* Docker ps

````
root@uminion2:~# docker ps
CONTAINER ID        IMAGE                       COMMAND                CREATED             STATUS              PORTS               NAMES
d8af046eb71d        kubernetes/redis-slave:v2   "/bin/sh -c /run.sh"   About an hour ago   Up About an hour                        k8s_redis-slave.6c2bfd79_redis-slave-controller-gziey_default_1b73f489-d101-11e4-b0df-08002798dcaa_703e3e57   
b97808f62fae        kubernetes/pause:go         "/pause"               About an hour ago   Up About an hour                        k8s_POD.1b73ed2a_redis-slave-controller-gziey_default_1b73f489-d101-11e4-b0df-08002798dcaa_8fcf6dcb
````
````
root@uminion3:~# docker ps
CONTAINER ID        IMAGE                     COMMAND                CREATED             STATUS              PORTS               NAMES
2f92b652d508        dockerfile/redis:latest   "redis-server /etc/r   About an hour ago   Up About an hour                        k8s_redis-master.a607faa0_redis-master-controller-fplln_default_0e93429d-d101-11e4-b0df-08002798dcaa_44c22282   
ca9493e2eb05        kubernetes/pause:go       "/pause"               About an hour ago   Up About an hour                        k8s_POD.1b73ed2a_redis-master-controller-fplln_default_0e93429d-d101-11e4-b0df-08002798dcaa_8328d5c9  
````

**Comment by jainvipin** [comment]
@decker502 - thanks.

It seems like that underlay network (aka host network) is playing some role in creating a temp loop here. That will cause the redis-server to slave connectivity issue you mentioned here. Can you please check if any other interfaces are not accidentally turned on and/or some other static routes are not installed, etc. Meanwhile, let me also try out the latest version myself and get back by today.

**Comment by decker502** [comment]
@jainvipin - thanks. 
I will also check if something can be found.

**Comment by decker502** [comment]
I find the same as issue [#1233](https://github.com/GoogleCloudPlatform/kubernetes/issues/1233)
