### ISSUE TITLE
Metrics not being collected (AWS?)

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#6484]
Running on AWS/Ubuntu, I see this in the kublet logs:

```
I0406 20:54:53.304045    7747 server.go:672] GET /stats/: (2.982104ms) 0 [[Go 1.1 package http] 172.20.0.11:55879]
I0406 20:54:53.328873    7747 server.go:158] HTTP InternalServerError: Internal Error: unable to find data for container /docker/5b0a0a8d384cadd9ec89e0ef902da9daa2f1c249d53d4feb3bda6e00f8c63110
I0406 20:54:53.329008    7747 server.go:672] GET /stats/default/fluentd-to-elasticsearch-ip-172-20-0-10/eeddeb2f-dc9e-11e4-8d46-0251ca363eb2/fluentd-es: (3.161006ms) 500
goroutine 195 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc2089d2a80, 0x1f4)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:188 +0x9a
net/http.Error(0x7fee35ede8b8, 0xc2089d2a80, 0xc208a63300, 0x7a, 0x1f4)
        /usr/src/go/src/net/http/server.go:1274 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).error(0xc2081b8ee0, 0x7fee35ede8b8, 0xc2089d2a80, 0x7fee35eaed00, 0xc2087a5a00)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:159 +0x213
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).serveStats(0xc2081b8ee0, 0x7fee35ede8b8, 0xc2089d2a80, 0xc208a3dad0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:720 +0x781
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).handleStats(0xc2081b8ee0, 0x7fee35ede8b8, 0xc2089d2a80, 0xc208a3dad0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:341 +0x46
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.*Server.(github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.handleStats)·fm(0x7fee35ede8b8, 0xc2089d2a80, 0xc208a3dad0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:84 +0x45
net/http.HandlerFunc.ServeHTTP(0xc2081ae2f0, 0x7fee35ede8b8, 0xc2089d2a80, 0xc208a3dad0)
        /usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc2082592f0, 0x7fee35ede8b8, 0xc2089d2a80, 0xc208a3dad0)
        /usr/src/go/src/net/http/server.go:1541 +0x17d
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).ServeHTTP(0xc2081b8ee0, 0x7fee35ecb110, 0xc208458d20, 0xc208a3dad0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_outp [[Go 1.1 package http] 172.20.0.11:55879]
```

The message repeats for each pod.  I don't think I'm getting any statistics into influxdb, but I may be looking in the wrong place.

Has anyone seen this?  I presume this isn't happening on GCE?  Any hints/ideas?

**Comment by vishh** [comment]
We have an e2e test under `test/e2e/monitoring.go` to cover the monitoring
pipeline. That helps filter out monitoring issues in GCE. Can you run that
test on your cluster and see if it passes?

**Comment by justinsb** [comment]
I think I've tracked this down...

On AWS, the root partition is often really small.  So I set Docker up to use /mnt/docker instead of /var/lib/docker.

I didn't tell cAdvisor though.  If we were running cadvisor standalone I could pass docker_root, but I'm not quite sure how to do that with the kubelet embedding.

I think I'm going to do a symlink from /var/lib/docker -> /mnt/docker; it will close off a whole set of problems.

**Comment by vmarmol** [comment]
FWIW, there is a `--docker_root` in the Kubelet

**Comment by justinsb** [comment]
Thanks @vmarmol ... may be a little tricky to work that through Salt (because we don't easily know if the AWS instance has additional storage until we boot it), but I'll check it out.

The symlink seems to have worked though!

**Comment by vishh** [comment]
@justinsb: Does the default monitoring setup work in AWS now?

**Comment by justinsb** [comment]
It does, with #6523.  Thanks for the ping.  Closing.
