### ISSUE TITLE
E2E tests: defer Ginko failure properly in shell.go

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#6500]
(PR on the way) 

Right now, running e2e from outside kubernetes root dir gives me  a very cryptic error.
 
```
goroutine 1 [running]:
github.com/onsi/ginkgo.Fail(0xc2080a02c0, 0xa2, 0x0, 0x0, 0x0)
        /var/lib/jenkins/workspace/kubernetes/Godeps/_workspace/src/github.com/onsi/ginkgo/ginkgo_dsl.go:229 +0xed
github.com/GoogleCloudPlatform/kubernetes/test/e2e.func·016()
        /var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/shell.go:40 +0x1b1
github.com/onsi/ginkgo/internal/suite.(*Suite).PushContainerNode(0xc20804a5a0, 0xa343d0, 0x5, 0xb81a28, 0x0, 0xd3d8b9, 0x76, 0x31, 0xc208039040, 0x1a0)
        /var/lib/jenkins/workspace/kubernetes/Godeps/_workspace/src/github.com/onsi/ginkgo/internal/suite/suite.go:132 +0x2d3
github.com/onsi/ginkgo.Describe(0xa343d0, 0x5, 0xb81a28, 0x73)
        /var/lib/jenkins/workspace/kubernetes/Godeps/_workspace/src/github.com/onsi/ginkgo/ginkgo_dsl.go:256 +0x8e
github.com/GoogleCloudPlatform/kubernetes/test/e2e.init()
        /var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/shell.go:49 +0x64c
main.init()
        /var/lib/jenkins/workspace/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/e2e/e2e.go:67 +0x54

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xf61f40)
        /var/lib/jenkins/workspace/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
        /var/lib/jenkins/workspace/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 9 [syscall]:
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35
```

**Comment by rjnagal** [comment]
the fix was merged.

**Comment by jayunit100** [comment]
ack yup thanks
