### ISSUE TITLE
AWS cluster setup error 

### ISSUE THREAD

**Issue by SaikiranDaripelli** [GoogleCloudPlatform/kubernetes#6575]
I am getting below error when setting up a new cluster on aws,
I am following below document and running from mac.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws.md

```
Waiting 3 minutes for cluster to settle
..................Re-running salt highstate
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ValueError: unknown locale: UTF-8
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 241, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 190, in run
    self._output_ret(ret_, out)
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 244, in _output_ret
    salt.output.display_output(ret, out, self.config)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 44, in display_output
    display_data = get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 74, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 209, in _format_host
    comment = salt.utils.sdecode(ret['comment'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 2495, in sdecode
    encodings = get_encodings()
  File "/usr/lib/python2.7/dist-packages/salt/utils/decorators/__init__.py", line 193, in _memoize
    cache[args] = func(*args)
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 2479, in get_encodings
    loc = locale.getdefaultlocale()[-1]
  File "/usr/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 241, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 190, in run
    self._output_ret(ret_, out)
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 244, in _output_ret
    salt.output.display_output(ret, out, self.config)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 44, in display_output
    display_data = get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 74, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 209, in _format_host
    comment = salt.utils.sdecode(ret['comment'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 2495, in sdecode
    encodings = get_encodings()
  File "/usr/lib/python2.7/dist-packages/salt/utils/decorators/__init__.py", line 193, in _memoize
    cache[args] = func(*args)
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 2479, in get_encodings
    loc = locale.getdefaultlocale()[-1]
  File "/usr/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

**Comment by SaikiranDaripelli** [comment]
Got it working by "export LC_CTYPE=en_EN.UTF-8" , 
This might still be an issue in scripts.
