### ISSUE TITLE
Scheduler is crashing when profiling is switched on

### ISSUE THREAD

**Issue by wojtek-t** [GoogleCloudPlatform/kubernetes#6621]
panic: http: multiple registrations for /debug/pprof/
goroutine 11 [running]:
net/http.(ServeMux).Handle(0xc20800a8a0, 0x9e9490, 0xd, 0x7f7d12f190a0, 0xb0e7c0)
/usr/src/go/src/net/http/server.go:1557 +0x244
net/http.(ServeMux).HandleFunc(0xc20800a8a0, 0x9e9490, 0xd, 0xb0e7c0)
/usr/src/go/src/net/http/server.go:1585 +0x6d
net/http.HandleFunc(0x9e9490, 0xd, 0xb0e7c0)
/usr/src/go/src/net/http/server.go:1597 +0x48
github.com/GoogleCloudPlatform/kubernetes/plugin/cmd/kube-scheduler/app.func·001()
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/plugin/cmd/kube-scheduler/app/server.go:84 +0x58
created by github.com/GoogleCloudPlatform/kubernetes/plugin/cmd/kube-scheduler/app.(*SchedulerServer).Run
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/plugin/cmd/kube-scheduler/app/server.go:90 +0x1c7

**Comment by wojtek-t** [comment]
cc @fgrzadkowski @timothysc
