### ISSUE TITLE
'minion_regexp' flag makes controller-manager crash

### ISSUE THREAD

**Issue by antoineco** [GoogleCloudPlatform/kubernetes#6880]
Since v0.15.0, passing a non-empty `--minion_regexp` flag to kube-controller-manager makes it fail on CoreOS with the following stack trace:

```
I0415 23:08:15.522753    1226 nodecontroller.go:118] Sending events to api server.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x586288]

goroutine 1 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/aws.(*AWSCloud).getInstancesByRegex(0x0, 0x7fff7350dd33, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/aws/aws.go:352 +0xf68
github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/aws.(*AWSCloud).List(0x0, 0x7fff7350dd33, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/aws/aws.go:407 +0x6c
github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller.(*NodeController).GetCloudNodesWithSpec(0xc20811e0e0, 0xc2080655c0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller/nodecontroller.go:627 +0x11b
github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller.(*NodeController).Run(0xc20811e0e0, 0x2540be400, 0x7fff7350dd01)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller/nodecontroller.go:159 +0xab
github.com/GoogleCloudPlatform/kubernetes/cmd/kube-controller-manager/app.(*CMServer).Run(0xc20809adc0, 0xc20804d620, 0x0, 0x6, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:205 +0xa82
main.main()
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kube-controller-manager/controller-manager.go:51 +0xd0

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1037da0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 9 [runnable]:
text/template/parse.lexText(0xc208036300, 0xdd0a38)
	/usr/src/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc208036300)
	/usr/src/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/src/go/src/text/template/parse/lex.go:191 +0x1ac

goroutine 10 [runnable]:
github.com/GoogleCloudPlatform/kubernetes/pkg/util.Forever(0xdcfda8, 0x12a05f200)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:92
created by github.com/GoogleCloudPlatform/kubernetes/pkg/util.InitLogs
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/logs.go:49 +0x9f

goroutine 11 [runnable]:
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).run(0xc20808f0e0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:93
created by github.com/GoogleCloudPlatform/kubernetes/pkg/util.NewTokenBucketRateLimiter
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:50 +0x81

goroutine 12 [runnable]:
github.com/GoogleCloudPlatform/kubernetes/cmd/kube-controller-manager/app.func·001()
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:169
created by github.com/GoogleCloudPlatform/kubernetes/cmd/kube-controller-manager/app.(*CMServer).Run
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:177 +0x2f9

goroutine 13 [runnable]:
github.com/GoogleCloudPlatform/kubernetes/pkg/util.Forever(0xc208065360, 0x2540be400)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:92
created by github.com/GoogleCloudPlatform/kubernetes/cmd/kube-controller-manager/app.(*CMServer).Run
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:180 +0x3fb

goroutine 14 [runnable]:
github.com/GoogleCloudPlatform/kubernetes/pkg/util.Forever(0xc20808f160, 0x12a05f200)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:92
created by github.com/GoogleCloudPlatform/kubernetes/pkg/controller.(*ReplicationManager).Run
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/controller/replication_controller.go:119 +0x127

goroutine 15 [runnable]:
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).run(0xc20808f280)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:93
created by github.com/GoogleCloudPlatform/kubernetes/pkg/util.NewTokenBucketRateLimiter
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:50 +0x81

goroutine 16 [runnable]:
github.com/GoogleCloudPlatform/kubernetes/pkg/watch.(*Broadcaster).loop(0xc208121080)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/watch/mux.go:155
created by github.com/GoogleCloudPlatform/kubernetes/pkg/watch.NewBroadcaster
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/watch/mux.go:70 +0xf8

goroutine 17 [runnable]:
github.com/GoogleCloudPlatform/kubernetes/pkg/client/record.func·003()
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/record/event.go:208
created by github.com/GoogleCloudPlatform/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/record/event.go:223 +0x119

```

**Comment by erictune** [comment]
crash is in AWS cloud provider.
@justinsb you touched this last.  Wanna take a look?

**Comment by erictune** [comment]
low prio since workaround is to stop passing that flag.

**Comment by antoineco** [comment]
I just tried using the GCE provider and also get a runtime error: https://gist.github.com/antoineco/bd1bc5c2efaa015ea700

**Comment by justinsb** [comment]
Weird.  I had a look but didn't immediately see a problem.  I will look again in more detail tomorrow.  (I did spot a bug I introduced where if you passed --minion_regexp=' it would probably crash, but I don't think that is what is happening here!)

The GCE report is also weird.  I think 0.15 introduced containerizing the kube-controller-manager.  I wonder if CoreOS blocks access from containers to the metadata service (169.254.169.254).  We _should_ be blocking that from non-privileged containers, so it wouldn't surprise me if CoreOS was actually doing the right thing here..  (My hypothesis is that this would cause initialization of the cloud provider to fail, and maybe we're not catching this properly.)  I'll look tomorrow....

**Comment by justinsb** [comment]
On second thoughts, I don't think we did containerize in 0.15.  So scratch that idea.

@antoineco: is there anything else in the log file?  I've looked at the code a bunch of different ways, and can't spot the problem.  I'm not entirely sure how to read golang stack trace arguments, but it looks like the "this" pointer to List is nil in both cases.  But that doesn't make a whole lot of sense.  I'm hoping there might be a clue in the log file.

minion_regexp is the default for AWS, so e.g. we run e2e tests with it.  So I'm kind of perplexed that it would be (this) broken!

**Comment by antoineco** [comment]
Yeah I'm also surprised, the exact same binary works just fine on Ubuntu
using the same flags. Seems to be a platform specific issue, I guess my
best bet is to try an older CoreOS version.

Regarding the logs, unfortunately that's all I have, the error pops out
immediately (CoreOS 647, btw)

**Comment by antoineco** [comment]
I got it. What triggers the panic is not the flag itself, but rather the format of the cloud provider conf file.

I was still using the previous one with Regions instead of Zones. In `/etc/aws.conf` I simply replaced `Region = eu-west-1` by `Zone = eu-west-1a` and my service started.

I guess we can close the ticket, but maybe also consider handling the error in a more appropriate way.

**Comment by justinsb** [comment]
Ah - thank you for tracking it down!  I'm so sorry for that behaviour.  I'm not entirely sure where it is coming from, but I'll reproduce it and fix it (tomorrow / this weekend).

**Comment by antoineco** [comment]
I don't think this issue is relevant anymore, whoever reads my comment feel free to review and close.

**Comment by roberthbailey** [comment]
`minion_regexp` was deprecated in https://github.com/GoogleCloudPlatform/kubernetes/pull/8704 and later removed.
