### ISSUE TITLE
Apiserver root url stacktraces on gce

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#7441]
Confusing stack traces from my apiserver logs:
```
I0428 15:42:46.748193       1 handlers.go:135] GET /: (79.052µs) 401
goroutine 87547 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20a571980, 0x191)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:188 +0x9a
net/http.Error(0x7fabc5a246f8, 0xc20a571980, 0xe491f0, 0xc, 0x191)
        /usr/src/go/src/net/http/server.go:1274 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/auth/handlers.unauthorized(0x7fabc5a246f8, 0xc20a571980, 0xc208f23450)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/auth/handlers/handlers.go:56 +0x4e
net/http.HandlerFunc.ServeHTTP(0x1059058, 0x7fabc5a246f8, 0xc20a571980, 0xc208f23450)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/GoogleCloudPlatform/kubernetes/pkg/auth/handlers.func·001(0x7fabc5a246f8, 0xc20a571980, 0xc208f23450)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/auth/handlers/handlers.go:39 +0x2f7
net/http.HandlerFunc.ServeHTTP(0xc20869e9c0, 0x7fabc5a246f8, 0xc20a571980, 0xc208f23450)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/GoogleCloudPlatform/kubernetes/pkg/api.func·019(0x7fabc5a246f8, 0xc20a571980, 0xc208f23450)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/requestcontext.go:101 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc208354660, 0x7fabc5a246f8, 0xc20a571980, 0xc208f23450)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/GoogleCloudPlatform/kubernetes/pkg/api.func·019(0x7fabc5a246f8, 0xc20a571980, 0xc208f23450)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/requestcontext.go:101 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc2089cf240, 0x7fabc5a246f8, 0xc20a571980, 0xc208f23450)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/GoogleCloudPlatform/kubernetes/pkg/apise [[Amazon Route 53 Health Check Service; ref:20c5467b-15fc-4685-aa32-bda940472afe; report http://amzn.to/1vsZADi] 54.245.168.9:47865]

```

Haven't dug too deep, @roberthbailey (just because it seem related to gce/amazon)

**Comment by a-robinson** [comment]
Why in the world would the apiserver be doing anything with Route 53?

**Comment by roberthbailey** [comment]
What you are seeing is the http user agent that is hitting your api server. Here's a log from when I point chrome at my API server:

```
I0429 21:24:49.118322       1 handlers.go:135] GET /: (80.18µs) 401
goroutine 2447 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc209171260, 0x191)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatfor
m/kubernetes/pkg/httplog/log.go:188 +0x9a
net/http.Error(0x7fa7a382c958, 0xc209171260, 0xe9c430, 0xc, 0x191)
        /usr/src/go/src/net/http/server.go:1274 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/auth/handlers.unauthorizedBasicAuth(0x7fa7a382c958, 0xc209171260, 0
xc208fd56c0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatfor
m/kubernetes/pkg/auth/handlers/handlers.go:62 +0x99
net/http.HandlerFunc.ServeHTTP(0x10c0280, 0x7fa7a382c958, 0xc209171260, 0xc208fd56c0)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/GoogleCloudPlatform/kubernetes/pkg/auth/handlers.func·001(0x7fa7a382c958, 0xc209171260, 0xc208fd56c0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatfor
m/kubernetes/pkg/auth/handlers/handlers.go:39 +0x2f7
net/http.HandlerFunc.ServeHTTP(0xc208604420, 0x7fa7a382c958, 0xc209171260, 0xc208fd56c0)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/GoogleCloudPlatform/kubernetes/pkg/api.func·019(0x7fa7a382c958, 0xc209171260, 0xc208fd56c0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatfor
m/kubernetes/pkg/api/requestcontext.go:101 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc2083ab7a0, 0x7fa7a382c958, 0xc209171260, 0xc208fd56c0)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/GoogleCloudPlatform/kubernetes/pkg/api.func·019(0x7fa7a382c958, 0xc209171260, 0xc208fd56c0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatfor
m/kubernetes/pkg/api/requestcontext.go:101 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc2089d9380, 0x7fa7a382c958, 0xc209171260, 0xc208fd56c0)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/GoogleCloudPlatform/kubernetes/p [[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gec
ko) Chrome/42.0.2311.135 Safari/537.36] 74.125.59.6:37223]
```

and you see a similar stack trace resulting in a 401 (unauthorized) response. For an authenticated request (e.g. from a master component), you should see something like:

```
I0429 21:24:59.259492       1 handlers.go:135] GET /api/v1beta3/nodes: (1.791351ms) 200 [[kube-controller-manager /v0.16.0 (linux/amd64) kubernetes/134e585] 127.0.0.1:33905]
```

I don't know why the Amazon health check service is hitting your apiserver, but it's being rejected with a 401 response.

**Comment by roberthbailey** [comment]
Is this reproducible or can we close it?

**Comment by bprashanth** [comment]
Haven't seen it since, will reopen if i do
