### ISSUE TITLE
Stack Trace on trying to read description of Persistent Volume

### ISSUE THREAD

**Issue by aronchick** [GoogleCloudPlatform/kubernetes#7604]
After I created a persistent volume, it throws an error on "describe".

```yml
kind: PersistentVolume
apiVersion: v1beta3
metadata:
  name: pVolumeName
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: "pv-disk"
    fsType: "ext4"
```

```
$ gcloud alpha container kubectl describe pv pVolumeName

ERROR: panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xb387c]

goroutine 1 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl.func·005(0x2208c2f640, 0x208dbc200, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/describe.go:292 +0x47c
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl.tabbedString(0x208e09b40, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource_printer.go:722 +0x14e
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl.(*PersistentVolumeDescriber).Describe(0x208cab470, 0x0, 0x0, 0x7fff5fbff320, 0x3, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/describe.go:295 +0x121
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd.RunDescribe(0x208c8ab60, 0x2208c1ac30, 0x208c56008, 0x208c92f20, 0x208c9e600, 0x2, 0x4, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/describe.go:77 +0x4d7
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd.func·008(0x208c92f20, 0x208c9e600, 0x2, 0x4)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/describe.go:38 +0x5f
github.com/spf13/cobra.(*Command).execute(0x208c92f20, 0x208c9e500, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:442 +0x410
github.com/spf13/cobra.(*Command).Execute(0x208c92c60, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:507 +0x51b
main.main()
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kubectl/kubectl.go:30 +0x104

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xaf3380)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 9 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 10 [select]:
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).step(0x208daf680, 0x1)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:102 +0xfc
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).run(0x208daf680)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:95 +0x28
created by github.com/GoogleCloudPlatform/kubernetes/pkg/util.NewTokenBucketRateLimiter
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:50 +0x81

goroutine 17 [IO wait]:
net.(*pollDesc).Wait(0x208db9100, 0x72, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0x208db9100, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0x208db90a0, 0x208c66c00, 0x400, 0x400, 0x0, 0x2208c1b158, 0x208cabc80)
	/usr/src/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0x208c56178, 0x208c66c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0x208cad080, 0x2208c2e518, 0x208c56178, 0x5, 0x0, 0x0)
	/usr/src/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0x208c72580, 0x17, 0x0, 0x0)
	/usr/src/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0x208c72580, 0x208d23000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/src/go/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x2208c2e8f8, 0x208c72580, 0x208c419c8, 0x208d23000, 0x1000, 0x1000, 0x5cd960, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0x208dae080, 0x208d23000, 0x1000, 0x1000, 0x208c1a000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0x208db20c0)
	/usr/src/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0x208db20c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0x208c41970)
	/usr/src/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:660 +0xc9f

goroutine 18 [select]:
net/http.(*persistConn).writeLoop(0x208c41970)
	/usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by markturansky** [comment]
Thanks for reporting this.  #7529 will fix this nil pointer bug.

The problem is your volume is not yet bound, but the command line wants to show you some info from the bound claim, except there isn't one.

**Comment by jlowdermilk** [comment]
@markturansky, do you want to break out 719bdb5d082442c935a05f97ac926ef845c815e6 as a separate pr to fix this, since the nil deref sort of a standalone bug?

**Comment by markturansky** [comment]
@jlowdermilk done.  #7676.
