### ISSUE TITLE
Kubelet crash

### ISSUE THREAD

**Issue by lavalamp** [GoogleCloudPlatform/kubernetes#7795]
I think this is the root cause of the problems in #7697.

My cluster does not appear to be recovering from this.

```
I0505 16:02:47.639343   30805 server.go:233] Using root directory: /var/lib/kubelet
I0505 16:02:47.752861   30805 manager.go:106] cAdvisor running in container: "/"
I0505 16:02:47.753274   30805 fs.go:87] Filesystem partitions: map[/dev/disk/by-uuid/96b86d97-40a1-4181-82c1-1c5558bac1e6:{mountpoint:/ major:8 minor:1}]
I0505 16:02:47.755417   30805 machine.go:223] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
I0505 16:02:47.755461   30805 manager.go:127] Machine: {NumCores:1 CpuFrequency:2299958 MemoryCapacity:1787035648 MachineID: SystemUUID:554F4E90-C7FF-B2FC-D9F4-17B0ACABA641 BootID:40079502-aaf2-4b93-b76d-d2d3fc3b215b Filesystems:[{Device:/dev/disk/by-uuid/96b86d97-40a1-4181-82c1-1c5558bac1e6 Capacity:105553100800}] DiskMap:map
[8:0:{Name:sda Major:8 Minor:0 Size:107374182400 Scheduler:cfq}] NetworkDevices:[{Name:cbr0 MacAddress:6e:dd:13:e1:66:20 Speed:0 Mtu:1460} {Name:eth0 MacAddress:42:01:0a:f0:90:de Speed:0 Mtu:1460}] Topology:[{Id:0 Memory:1787035648 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Lev
el:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:47185920 Type:Unified Level:3}]}]}
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f6bfa192165
goroutine 0 [idle]:
goroutine 6 [syscall]:
runtime.notetsleepg(0x18a1b38, 0x6fbb38fd9, 0x0)
        /usr/src/go/src/runtime/lock_futex.go:201 +0x52 fp=0xc208017f68 sp=0xc208017f40
runtime.timerproc()
        /usr/src/go/src/runtime/time.go:207 +0xfa fp=0xc208017fe0 sp=0xc208017f68
runtime.goexit()
        /usr/src/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208017fe8 sp=0xc208017fe0
created by runtime.addtimerLocked
        /usr/src/go/src/runtime/time.go:113 +0x1ba
goroutine 1 [runnable, locked to thread]:
os.Open(0x108a110, 0x19, 0x2, 0x2, 0xc208030780)
        /usr/src/go/src/os/file.go:238
os.hostname(0x0, 0x0, 0x0, 0x0)
        /usr/src/go/src/os/sys_linux.go:10 +0x9f
os.Hostname(0x0, 0x0, 0x0, 0x0)
        /usr/src/go/src/os/doc.go:93 +0x43
github.com/golang/glog.init·2()
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog_file.go:58 +0x1f
github.com/golang/glog.init()
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog_file.go:124 +0x23b
github.com/GoogleCloudPlatform/kubernetes/pkg/util.init()
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/validation.go:97 +0x86
main.init()
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kubelet/kubelet.go:50 +0x4c
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/src/go/src/runtime/asm_amd64.s:2232 +0x1
goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x18a2060)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7
rax     0x0
rbx     0x7f6bfa4e5d98
rcx     0xffffffffffffffff
rdx     0x6
rdi     0x792b
rsi     0x792f
rbp     0xbcfb12
rsp     0x7f6bf995d9d8
r8      0xa
r9      0x7f6bf995e700
r10     0x8
r11     0x206
r12     0x1a80010
r13     0x3
r14     0x7f6bfa927040
r15     0x3
rip     0x7f6bfa192165
rflags  0x206
cs      0x33
fs      0x0
gs      0x0
```

To dawn to find an owner.

**Comment by bprashanth** [comment]
Fyi I have seen similar stack traces (pthread_create failing, can't be sure if it's identical) when you have > 50 pods on the node.

**Comment by dchen1107** [comment]
Can I access the node in bad state? Looks like kubelet was crashed at init time. Monit should restart kubelet every 2 mins. Is this a crashloop? When you said this is the root cause of #7697 because this happens to a lot of nodes in a cluster? so that rc or node controller ping-pong the workloads?
