### ISSUE TITLE
api returns error 415 on PATCH

### ISSUE THREAD

**Issue by nebelpfade** [GoogleCloudPlatform/kubernetes#8489]
PATCH http://IP:8080/api/v1beta3/namespaces/dev-43b46323-ea6f-49cb-b5bb-2f9489cc61a1/replicationcontrollers/redis-master
{"spec":{"replicas":0}}

answer:
{
 "kind": "Status",
 "apiVersion": "v1beta3",
 "metadata": {},
 "status": "Failure",
 "message": "the server responded with the status code 415 but did not return more information",
 "details": {},
 "code": 415
}

Before v0.15.0 it had worked well.

**Comment by nikhiljindal** [comment]
That error is returned by go-restful because it did not find any valid route with the same content type as specified in the request: https://github.com/emicklei/go-restful/blob/977ac8fcbcd2ee33319246f7c91d4b426402dc70/jsr311.go#L71

Can you try setting the content-type in your request as is described here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api-conventions.md#patch-operations

cc @ghodss

**Comment by sroze** [comment]
@nikhiljindal well, I've the same issue which is not fixed by setting the `Content-Type` value, at least with the "strategic merge patch".

Here's the request:
```http
PATCH /api/v1beta3/namespaces/connected-adventure/replicationcontrollers/app
Host: 1.2.3.4:6443
Content-Type: application/strategic-merge-json-patch+json
User-Agent: Guzzle/5.3.0 curl/7.37.1 PHP/5.6.8
Content-Length: 25

{"spec": {"replicas": 5}}
```

Here's the response body:
```json
{ "kind": "Status", "apiVersion": "v1beta3", "metadata": {}, "status": "Failure", "message": "the server responded with the status code 415 but did not return more information", "details": {}, "code": 415 }
```

And here's the log trace of the request in the apiserver pod:
```
goroutine 425070 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc209060ba0, 0x19f)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:188 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.writeJSON(0x19f, 0x7ff845b738f0, 0xc20d190820, 0x7ff845b73b08, 0xc20d2fd780, 0x7ff8459bd5b8, 0xc209060ba0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:284 +0x232
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.errorJSON(0x7ff845b77e90, 0xc20d2fd700, 0x7ff845b738f0, 0xc20d190820, 0x7ff8459bd5b8, 0xc209060ba0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:291 +0xa3
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.serviceErrorHandler(0xc208719800, 0xc208717e40, 0x3, 0x4, 0x19f, 0x12fd4d0, 0x1b, 0xc20b836180, 0xc20c0b1630)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:203 +0x3c2
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·004(0x19f, 0x12fd4d0, 0x1b, 0xc20b836180, 0xc20c0b1630)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:185 +0x63
github.com/emicklei/go-restful.func·004(0xc20b836180, 0xc20c0b1630)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:198 +0xfb
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20b836150, 0xc20b836180, 0xc20c0b1630)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
github.com/emicklei/go-restful.(*Container).dispatch(0xc20808ff10, 0x7ff8459bd5b8, 0xc209060ba0, 0xc208b3add0)
	/go/ [[Guzzle/5.3.0 curl/7.37.1 PHP/5.6.8] 141.0.34.138:21577]
```

**Comment by sroze** [comment]
Come from a typo, purposed PR here:
https://github.com/GoogleCloudPlatform/kubernetes/pull/8913

**Comment by sroze** [comment]
Btw, I'm still having strange issues with sub-objects. Note that it appears only is the sub-object is already set.

Here's the request:
```json
{
    "spec": {
        "templateRef": {
            "kind": "PodTemplate",
            "name": "foo"
        }
    }
}
```

Here's the API log:
```
E0528 12:47:05.624664       1 errors.go:66] apiserver received an error that is not an api.Status: merging an object in json but data type is not map or struct, instead is: ptr
I0528 12:47:05.624777       1 handlers.go:135] PATCH /api/v1beta3/namespaces/connected-adventure/replicationcontrollers/app: (957.849µs) 500
goroutine 937133 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc209d983c0, 0x1f4)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:188 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7ff845b738f0, 0xc2080a65c0, 0x7ff845b73b08, 0xc2099f3e00, 0x7ff8459bd5b8, 0xc209d983c0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:284 +0x232
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.errorJSON(0x7ff845b6ee00, 0xc209b90c20, 0x7ff845b738f0, 0xc2080a65c0, 0x7ff8459bd5b8, 0xc209d983c0, 0x5a)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:291 +0xa3
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·026(0xc209a096e0, 0xc20b330f50)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:394 +0xaf0
github.com/emicklei/go-restful.func·005(0xc209a096e0, 0xc20b330f50)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:215 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc209a09950, 0xc209a096e0, 0xc20b330f50)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·003(0xc209a096e0, 0xc20b330f50, 0xc209a09950)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:95 +0x88
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc209a09950, 0xc209a096e0, 0xc20b330f50)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/g [[Guzzle/5.3.0 curl/7.37.1 PHP/5.6.8] 1.2.3.4:10801]
```

**Comment by bgrant0607** [comment]
Looks like a bug in strategic merge -- it doesn't deal with pointers correctly:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/third_party/forked/json/fields.go#L28

**Comment by bgrant0607** [comment]
cc @ghodss

**Comment by satnam6502** [comment]
@bgrant0607 is it possible to have a milestone for this so I can tell if I should merger #9806? Thanks.
