### ISSUE TITLE
'vagrant halt && cluster/kube-up.sh' results in 'salt: error: no such option: --show-timeout'

### ISSUE THREAD

**Issue by MaxDaten** [GoogleCloudPlatform/kubernetes#8660]
I setup kubernetes as described here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/vagrant.md

booting up the cluster is successful. but halting and rebooting the cluster via `cluster/kube-up.sh` results in an error:

```
...
==> master: Executing configuration
==> master: kubernetes-master:
==> master:     True
==> master: kubernetes-minion-1:
==> master:     Minion did not return. [No response]
==> master: Usage: salt [options] '<target>' <function> [arguments]
==> master: 
==> master: salt: error: no such option: --show-timeout
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by thomschke** [comment]
same problem

I suppose it does something wrong during installation of minion-1,
pod 'kube-dns-o5rls' is PENDING:

```
Waiting for each minion to be registered with cloud provider
Validating we can run kubectl commands.
POD                                         IP        CONTAINER(S)              IMAGE(S)                                                                            HOST                 LABELS                                                STATUS    CREATED          MESSAGE
etcd-server-kubernetes-master                                                                                                                                       kubernetes-master/   <none>                                                Running   About a minute   
                                                      etcd-container            gcr.io/google_containers/etcd:2.0.9                                                                                                                            Running   About a minute   
kube-apiserver-kubernetes-master                                                                                                                                    kubernetes-master/   <none>                                                Running   About a minute   
                                                      kube-apiserver            gcr.io/google_containers/kube-apiserver:93a879cea6d76afcacc085bc7e138fcc                                                                                       Running   About a minute   
kube-controller-manager-kubernetes-master                                                                                                                           kubernetes-master/   <none>                                                Running   About a minute   
                                                      kube-controller-manager   gcr.io/google_containers/kube-controller-manager:e0d3b527de37e38320ce3ecc5982892d                                                                              Running   About a minute   
kube-dns-o5rls                                                                                                                                                      <unassigned>         k8s-app=kube-dns,kubernetes.io/cluster-service=true   Pending   About a minute   
                                                      etcd                      gcr.io/google_containers/etcd:2.0.9                                                                                                                                      
                                                      kube2sky                  gcr.io/google_containers/kube2sky:1.4                                                                                                                                    
                                                      skydns                    gcr.io/google_containers/skydns:2015-03-11-001                                                                                                                           
kube-scheduler-kubernetes-master                                                                                                                                    kubernetes-master/   <none>                                                Running   About a minute   
                                                      kube-scheduler            gcr.io/google_containers/kube-scheduler:60e7be27f99d4639ad22321025005983                                                                                       Running   About a minute   
```

and after that

```
... calling validate-cluster
Found 1 nodes.
     1	NAME         LABELS    STATUS
     2	10.245.1.3   <none>    Ready
Validate output:
NAME                 STATUS    MESSAGE   ERROR
scheduler            Healthy   ok        nil
etcd-0               Healthy   {"action":"get","node":{"dir":true,"nodes":[{"key":"/registry","dir":true,"modifiedIndex":3,"createdIndex":3}]}}
                     nil
controller-manager   Healthy   ok        nil
```

after installing, calling `vagrant ssh minion-1` works, but

```
$ ./kubectl.sh get minions
$
```

shows nothing :-(

**Comment by mcortinas** [comment]
Maybe, these issues is the same like https://github.com/GoogleCloudPlatform/kubernetes/issues/5739

**Comment by thomschke** [comment]
problem exists under 0.17+ (vagrant install under 0.16.2 works)

When I inspect the salt logs `/var/log/salt/minion` from a minion, then I can see:

```
2015-05-26 06:27:43,220 [salt.loader      ][DEBUG   ][2232] Error loading module.ipmi: No module named pyghmi.ipmi
2015-05-26 06:27:43,312 [salt.loader      ][DEBUG   ][2232] Error loading module.tls: ['PyOpenSSL must be installed before this module can be used.']
2015-05-26 06:27:43,325 [salt.loader      ][DEBUG   ][2232] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
2015-05-26 06:27:43,370 [salt.loader      ][DEBUG   ][2232] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located

...

2015-05-26 06:27:43,567 [salt.loader      ][DEBUG   ][2232] Error loading states.ipmi: No module named pyghmi.ipmi
2015-05-26 06:27:43,568 [salt.loader      ][DEBUG   ][2232] Failed to import states container_bridge:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 951, in _load_module
    ), fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/states/container_bridge.py", line 20, in <module>
    import salt.utils.ipaddr as ipaddr
ImportError: No module named ipaddr
```

**Comment by derekwaynecarr** [comment]
This is fixed now
