### ISSUE TITLE
e2e GCE test failure/flake: Kubernetes e2e suite.ResizeNodes should be able to delete nodes.

### ISSUE THREAD

**Issue by dchen1107** [GoogleCloudPlatform/kubernetes#8940]
Looks like the test failed in recent run and it is a regression:

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/6460/testReport/junit/(root)/Kubernetes%20e2e%20suite/ResizeNodes_should_be_able_to_delete_nodes_/

Stacktrace

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/resize_nodes.go:292
Expected error:
    <*exec.ExitError | 0xc208a86c00>: {
        ProcessState: {
            pid: 17903,
            status: 256,
            rusage: {
                Utime: {Sec: 0, Usec: 320000},
                Stime: {Sec: 0, Usec: 68000},
                Maxrss: 44068,
                Ixrss: 0,
                Idrss: 0,
                Isrss: 0,
                Minflt: 21845,
                Majflt: 0,
                Nswap: 0,
                Inblock: 200,
                Oublock: 16,
                Msgsnd: 0,
                Msgrcv: 0,
                Nsignals: 0,
                Nvcsw: 96,
                Nivcsw: 33,
            },
        },
    }
    exit status 1
not to have occurred

I will take a look.

**Comment by bprashanth** [comment]
Fyi there seems to be a period of instability after the resize test that might leak into the next test. This happened in a local run and I found the kubelet logs full of:

```
I0528 17:21:37.741031    5636 server.go:588] POST /stats/container/: (18.656601ms) 0 [[Go 1.1 package http] 10.245.1.36:48636]
E0528 17:21:46.541746    5636 kubelet.go:1314] Error listing containers: &net.OpError{Op:"dial", Net:"unix", Addr:(*net.UnixAddr)(0xc2088d9ba0), Err:0x2}
E0528 17:21:46.541890    5636 kubelet.go:1628] Couldn't sync containers: dial unix /var/run/docker.sock: no such file or directory
I0528 17:21:48.103486    5636 server.go:154] HTTP InternalServerError: Internal Error: dial unix /var/run/docker.sock: no such file or directory
I0528 17:21:48.103567    5636 server.go:588] GET /stats/default/fluentd-elasticsearch-e2e-test-beeps-minion-eo45/e547efc5-055d-11e5-bb3b-42010af09e73/fluentd-elasticsearch: (203.794µs) 500
goroutine 147 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20811dbc0, 0x1f4)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:188 +0x9a
net/http.Error(0x7fbc5fc84938, 0xc20811dbc0, 0xc2085ae640, 0x49, 0x1f4)
	/usr/src/go/src/net/http/server.go:1274 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).error(0xc20801e2c0, 0x7fbc5fc84938, 0xc20811dbc0, 0x7fbc5fc7f700, 0xc2085b2440)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:155 +0x213
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).serveStats(0xc20801e2c0, 0x7fbc5fc84938, 0xc20811dbc0, 0xc2086df110)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:678 +0x78f
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).handleStats(0xc20801e2c0, 0x7fbc5fc84938, 0xc20811dbc0, 0xc2086df110)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:281 +0x46
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.*Server.(github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.handleStats)·fm(0x7fbc5fc84938, 0xc20811dbc0, 0xc2086df110)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/server.go:84 +0x45
net/http.HandlerFunc.ServeHTTP(0xc2083595d0, 0x7fbc5fc84938, 0xc20811dbc0, 0xc2086df110)
	/usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20835df80, 0x7fbc5fc84938, 0xc20811dbc0, 0xc2086df110)
	/usr/src/go/src/net/http/server.go:1541 +0x17d
github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*Server).ServeHTTP(0xc20801e2c0, 0x7fbc5fc84900, 0xc2088ac460, 0xc2086df110)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_outp [[Go 1.1 package http] 10.245.1.36:48636]
```

**Comment by dchen1107** [comment]
I couldn't reproduce the particular issue reported here and I believe this is same gingko clean up issue as #8935. But we do run into timeout issue sometimes. Closing this one.
