### ISSUE TITLE
kubetcl create service crashes when no apiVersion is provided

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#9224]
```
$ kubectl create --validate -f mytunes-service.yaml --namespace=mytunes
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/api/validation.(*SwaggerSchema).ValidateBytes(0x208efc000, 0x208f186c0, 0x10f, 0x11c, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/validation/schema.go:80 +0x36d
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/util.(*clientSwaggerSchema).ValidateBytes(0x208f6ae20, 0x208f186c0, 0x10f, 0x11c, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/util/factory.go:278 +0x334
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource.ValidateSchema(0x208f186c0, 0x10f, 0x11c, 0x2208d99678, 0x208f6ae20, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource/visitor.go:192 +0x1ee
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource.(*PathVisitor).Visit(0x208f59aa0, 0x208fcc5e0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource/visitor.go:215 +0x23b
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit(0x208f5bd60, 0x1, 0x1, 0x208fcc5a0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource/visitor.go:177 +0x17e
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource.(*EagerVisitorList).Visit(0x208fcc4e0, 0x208fcc5a0, 0x0, 0x0)
	<autogenerated>:97 +0xbd
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x2208d99f30, 0x208fcc4e0, 0x208f59a70, 0x208fcc560, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource/visitor.go:398 +0x10b
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource.(*FlattenListVisitor).Visit(0x208fcc500, 0x208fcc560, 0x0, 0x0)
	<autogenerated>:108 +0xbd
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x2208d99f58, 0x208fcc500, 0x208fcc520, 0x3, 0x4, 0x208fcc540, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource/visitor.go:350 +0x110
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource.(*DecoratedVisitor).Visit(0x208f59ad0, 0x208fcc540, 0x0, 0x0)
	<autogenerated>:121 +0xbc
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource.(*Result).Visit(0x208fe6b60, 0x208fcc540, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/resource/result.go:78 +0x73
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd.RunCreate(0x208dd6b00, 0x2208d85c30, 0x208dba008, 0x208e136a0, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/create.go:107 +0x534
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd.func·004(0x208db2000, 0x208dd2ac0, 0x0, 0x4)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/create.go:51 +0xbb
github.com/spf13/cobra.(*Command).execute(0x208db2000, 0x208dd2a80, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:476 +0x65c
github.com/spf13/cobra.(*Command).Execute(0x208e656c0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:541 +0x18d
main.main()
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kubectl/kubectl.go:30 +0x104

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xc345a0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 9 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 10 [select]:
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).step(0x208f6bd80, 0x1)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:102 +0xfc
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).run(0x208f6bd80)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:95 +0x28
created by github.com/GoogleCloudPlatform/kubernetes/pkg/util.NewTokenBucketRateLimiter
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:50 +0x81

goroutine 13 [IO wait]:
net.(*pollDesc).Wait(0x208fe6ed0, 0x72, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0x208fe6ed0, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0x208fe6e70, 0x208f72c00, 0x400, 0x400, 0x0, 0x2208d86090, 0x209000438)
	/usr/src/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0x208ffe000, 0x208f72c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0x208e383f0, 0x2208d9b0f0, 0x208ffe000, 0x5, 0x0, 0x0)
	/usr/src/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0x208fa8000, 0x17, 0x0, 0x0)
	/usr/src/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0x208fa8000, 0x208f6f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/src/go/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x2208d9b758, 0x208fa8000, 0x208dec318, 0x208f6f000, 0x1000, 0x1000, 0x67b840, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0x208f6bf00, 0x208f6f000, 0x1000, 0x1000, 0x208d84000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0x209045740)
	/usr/src/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0x209045740, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0x208dec2c0)
	/usr/src/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:660 +0xc9f

goroutine 14 [select]:
net/http.(*persistConn).writeLoop(0x208dec2c0)
	/usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:661 +0xcbc


satnam-macbookpro2:blog-logging satnam$ cat mytunes-service.yaml
kind: Service
metadata:
  name: mytunes
  namespace: mytunes
  labels:
    app: mytunes
spec:
  selector:
    app: mytunes
  ports:
  - name: db
    port: 9200
    targetPort: es
  - name: ui
    port: 5601
    targetPort: kibana
  createExternalLoadBalancer: true

satnam-macbookpro2:blog-logging satnam$ kubectl version
Client Version: version.Info{Major:"0", Minor:"17", GitVersion:"v0.17.0", GitCommit:"82f8bdac06ddfacf493a9ed0fedc85f5ea62ebd5", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"18+", GitVersion:"v0.18.0-116-g6b2a0c1226ba67-dirty", GitCommit:"6b2a0c1226ba67d066a942a304267ac598aa3f75", GitTreeState:"dirty"}
```

**Comment by satnam6502** [comment]
Pods and namespace were created fine.
```
satnam-macbookpro2:blog-logging satnam$  kubectl create -f mytunes-namespace.yaml
namespaces/mytunes
satnam-macbookpro2:blog-logging satnam$ kubectl create -f mytunes-pod-v1.yaml -- namespace=mytunes
pods/mytunes-v1
```

**Comment by satnam6502** [comment]
And thanks @erictune for your help re: namespaces.

**Comment by satnam6502** [comment]
@jlowdermilk

**Comment by bgrant0607** [comment]
No apiVersion.

**Comment by jlowdermilk** [comment]
Yeah, no apiVersion in the schema. The validator should still fail with a user friendly error that the apiVersion is required.

**Comment by satnam6502** [comment]
Ah, right! And indeed, we should not have a panic.

**Comment by satnam6502** [comment]
Works except for the ELB.
```
 make mkservice
kubectl create -f mytunes-service.yaml --namespace=mytunes
services/mytunes
satnam-macbookpro2:blog-logging satnam$ make get
kubectl get pods,services,endpoints --namespace=mytunes
POD       IP        CONTAINER(S)   IMAGE(S)   HOST      LABELS    STATUS    CREATED   MESSAGE
NAME      LABELS        SELECTOR      IP(S)          PORT(S)
mytunes   app=mytunes   app=mytunes   10.0.133.199   9200/TCP
                                                     5601/TCP
NAME      ENDPOINTS
mytunes   <none>
```

**Comment by bgrant0607** [comment]
Re-opening because we should fix the crash and generate an error message.

**Comment by satnam6502** [comment]
Fair enough.

**Comment by feihujiang** [comment]
And I also found that kubetcl create --validate crashes when no kind is provided. Hi, I wonder if any other has already started working on this? If not, I would volunteer myself to do this.
