### ISSUE TITLE
Service Controller Watch possible infinite loop during LB creation

### ISSUE THREAD

**Issue by uruddarraju** [GoogleCloudPlatform/kubernetes#9360]
I am using the openstack cloudprovider to bring up a cluster and create an external LB. I then ran into a weird problem and tried to debug a little and think found what the problem is, but there are a few things that I could not explain and have a theory that I want someone to refute.

This is the log I have in `kube-controller-manager`

```bash
Jun 05 05:54:55 kubernetes-master-7957 kube-controller-manager[11533]: I0605 05:54:55.844360   11533 servicecontroller.go:188] Got new Added delta for service: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:esfrontend GenerateName: Namespace:default SelfLink:/api/v1beta3/namespaces/default/services/esfrontend UID:8c3c215f-0b42-11e5-975c-74dbd1a077b0 ResourceVersion:2466 CreationTimestamp:2015-06-05 05:20:15 +0000 UTC DeletionTimestamp:<nil> Labels:map[name:elasticsearch] Annotations:map[]} Spec:{Ports:[{Name: Protocol:TCP Port:80 TargetPort:{Kind:0 IntVal:9200 StrVal:}}] Selector:map[name:elasticsearch role:load-balancer] PortalIP:10.247.142.19 CreateExternalLoadBalancer:true PublicIPs:[] SessionAffinity:None} Status:{}}
Jun 05 05:54:55 kubernetes-master-7957 kube-controller-manager[11533]: I0605 05:54:55.858084   11533 servicecontroller.go:268] Creating LB for service default/esfrontend
Jun 05 05:54:55 kubernetes-master-7957 kube-controller-manager[11533]: E0605 05:54:55.865276   11533 servicecontroller.go:153] Failed to process service delta. Retrying: failed to create external load balancer for service default/esfrontend: Unable able to find service matching lbname: a8c3c215f0b4211e5975c74dbd1a077b
Jun 05 05:54:56 kubernetes-master-7957 kube-controller-manager[11533]: I0605 05:54:56.054567   11533 servicecontroller.go:188] Got new Added delta for service: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:esfrontend GenerateName: Namespace:default SelfLink:/api/v1beta3/namespaces/default/services/esfrontend UID:77dba985-0b43-11e5-975c-74dbd1a077b0 ResourceVersion:2733 CreationTimestamp:2015-06-05 05:26:50 +0000 UTC DeletionTimestamp:<nil> Labels:map[name:esfrontend] Annotations:map[]} Spec:{Ports:[{Name: Protocol:TCP Port:80 TargetPort:{Kind:0 IntVal:9200 StrVal:}}] Selector:map[name:elasticsearch role:load-balancer] PortalIP:10.247.131.213 CreateExternalLoadBalancer:true PublicIPs:[] SessionAffinity:None} Status:{}}
Jun 05 05:54:56 kubernetes-master-7957 kube-controller-manager[11533]: I0605 05:54:56.073351   11533 servicecontroller.go:268] Creating LB for service default/esfrontend
Jun 05 05:54:56 kubernetes-master-7957 kube-controller-manager[11533]: E0605 05:54:56.088323   11533 servicecontroller.go:153] Failed to process service delta. Retrying: failed to create external load balancer for service default/esfrontend: Unable able to find service matching lbname: a77dba9850b4311e5975c74dbd1a077b
Jun 05 05:54:57 kubernetes-master-7957 kube-controller-manager[11533]: I0605 05:54:57.303412   11533 openstack.go:209] Claiming to support Instances
Jun 05 05:54:57 kubernetes-master-7957 kube-controller-manager[11533]: I0605 05:54:57.890623   11533 servicecontroller.go:188] Got new Added delta for service: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:elasticsearch GenerateName: Namespace:default SelfLink:/api/v1beta3/namespaces/default/services/elasticsearch UID:d53988ed-0b43-11e5-975c-74dbd1a077b0 ResourceVersion:2820 CreationTimestamp:2015-06-05 05:29:27 +0000 UTC DeletionTimestamp:<nil> Labels:map[name:elasticsearch] Annotations:map[]} Spec:{Ports:[{Name: Protocol:TCP Port:80 TargetPort:{Kind:0 IntVal:9200 StrVal:}}] Selector:map[name:elasticsearch role:load-balancer] PortalIP:10.247.109.7 CreateExternalLoadBalancer:true PublicIPs:[] SessionAffinity:None} Status:{}}
Jun 05 05:54:57 kubernetes-master-7957 kube-controller-manager[11533]: I0605 05:54:57.890930   11533 servicecontroller.go:235] Deleting existing load balancer for service default/elasticsearch that needs an updated load balancer.
Jun 05 05:54:57 kubernetes-master-7957 kube-controller-manager[11533]: I0605 05:54:57.962485   11533 servicecontroller.go:268] Creating LB for service default/elasticsearch
Jun 05 05:54:57 kubernetes-master-7957 kube-controller-manager[11533]: E0605 05:54:57.994480   11533 servicecontroller.go:153] Failed to process service delta. Retrying: failed to create external load balancer for service default/elasticsearch: Unable able to find service matching lbname: ad53988ed0b4311e5975c74dbd1a077b
```

As you can see it is basically an infinite loop where the servicecontroller is trying to create an LB after it has an Add delta on a external routable service and not able to find the service to get a list of endpoints (I am building my lb pool with the endpoints).  The sequence of events which led to this issue are as follows:

 1. Created an RC with 3 replicas
 2. Created a service with external LB => Placed on FIFO Queue as Added Delta
 3. Called Delete Service, which deleted the API server's service object of my service -> Placed on FIFO Queue as Deleted Delta
 4. processDelta Called for add event and CreateTCPLB failed due to a connection reset. Since this is retriable, the delta has been placed back on the queue.
 5. Now Deleted Delta is processed (There was nothing to be deleted, hence moved on, but the apiserver's service object has been deleted by now).
 6. Now the AddedDelta comes back up to get processed (for a service that no longer exists)

Is this an expected behavior ? I might not be the best at explaining this, but let me know if I can be more clear on this. 

And the Queue is 

    NewServiceCreate <- SomeOp <- NewServiceDelete <- SomeOp

The CreateTCPLB for the NewServiceCreated failed so added back to the queue. It is now:

    SomeOp <- NewServiceDelete <- SomeOpAgain <- NewServiceCreate

After a while:

    NewServiceDelete <- SomeOpAgain <- NewServiceCreated

After this, the service is completely deleted and now it is only 

    NewServiceCreated

Should we be processing this delta ? I ask this because, this delta has been undone by an other delta event before the Create Delta has been processed.

**Comment by uruddarraju** [comment]
You can reproduce this by:

1) Induce an error returned at CreateTCPLoadbalancer function in the cloudprovider
2) Build a cluster with this
3) Create a service (with externalLB set to true) on top of some pods.
4) Delete service

The 3rd step should fail and be set for retry.

**Comment by uruddarraju** [comment]
Eventually, I got a panic on the kube-controller-manager

```
Jun 06 05:47:54 kubernetes-master-7427 kube-controller-manager[4647]: I0606 05:47:54.261241    4647 servicecontroller.go:169] Got delta of service %!s(*api.Service=<nil>)
Jun 06 05:47:54 kubernetes-master-7427 kube-controller-manager[4647]: I0606 05:47:54.261255    4647 servicecontroller.go:173] Not OK
Jun 06 05:47:54 kubernetes-master-7427 kube-controller-manager[4647]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 06 05:47:54 kubernetes-master-7427 kube-controller-manager[4647]: [signal 0xb code=0x1 addr=0x0 pc=0x57d68a]
Jun 06 05:47:54 kubernetes-master-7427 kube-controller-manager[4647]: goroutine 102 [running]:
Jun 06 05:47:54 kubernetes-master-7427 kube-controller-manager[4647]: github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/servicecontroller.(*ServiceController).processDelta(0xc2085b0af0, 0xc20860ec40, 0x0, 0x0, 0x0)
Jun 06 05:47:54 kubernetes-master-7427 kube-controller-manager[4647]: /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/servicecontroller/servicecontroller.go:185 +0xc4a
```
